import TvmLean.Model

namespace TvmLean

/-- Minimal metadata needed by test scaffolding and coverage reporting. -/
structure InstrSpecRow where
  id : InstrId
  family : String
  deriving Repr, Inhabited, DecidableEq, BEq

/-- Full instruction list from the current pinned snapshot. Generated by `tools/gen_spec_index.py`. -/
def allInstrRows : Array InstrSpecRow := #[]

/-- Convenience projection of all known instruction IDs. -/
def allInstrIds : Array InstrId := allInstrRows.map (fun r => r.id)

end TvmLean
