-- Auto-generated by tools/gen_test_scaffold.py

import Tests.Harness.Registry
import Tests.Instr.Arith.ABS
import Tests.Instr.Arith.ADD
import Tests.Instr.Arith.ADDDIVMOD
import Tests.Instr.Arith.ADDDIVMODC
import Tests.Instr.Arith.ADDDIVMODR
import Tests.Instr.Arith.ADDINT
import Tests.Instr.Arith.ADDRSHIFTC_HASH_MOD
import Tests.Instr.Arith.ADDRSHIFTMOD
import Tests.Instr.Arith.ADDRSHIFTMODC
import Tests.Instr.Arith.ADDRSHIFTMODR
import Tests.Instr.Arith.ADDRSHIFTR_HASH_MOD
import Tests.Instr.Arith.ADDRSHIFT_HASH_MOD
import Tests.Instr.Arith.AND
import Tests.Instr.Arith.BITSIZE
import Tests.Instr.Arith.CHKNAN
import Tests.Instr.Arith.CMP
import Tests.Instr.Arith.DEC
import Tests.Instr.Arith.DIV
import Tests.Instr.Arith.DIVC
import Tests.Instr.Arith.DIVMOD
import Tests.Instr.Arith.DIVMODC
import Tests.Instr.Arith.DIVMODR
import Tests.Instr.Arith.DIVR
import Tests.Instr.Arith.EQINT
import Tests.Instr.Arith.EQUAL
import Tests.Instr.Arith.FITS
import Tests.Instr.Arith.FITSX
import Tests.Instr.Arith.GEQ
import Tests.Instr.Arith.GREATER
import Tests.Instr.Arith.GTINT
import Tests.Instr.Arith.INC
import Tests.Instr.Arith.ISNAN
import Tests.Instr.Arith.LEQ
import Tests.Instr.Arith.LESS
import Tests.Instr.Arith.LESSINT
import Tests.Instr.Arith.LSHIFT
import Tests.Instr.Arith.LSHIFTADDDIVMOD
import Tests.Instr.Arith.LSHIFTADDDIVMODC
import Tests.Instr.Arith.LSHIFTADDDIVMODR
import Tests.Instr.Arith.LSHIFTDIV
import Tests.Instr.Arith.LSHIFTDIVC
import Tests.Instr.Arith.LSHIFTDIVMOD
import Tests.Instr.Arith.LSHIFTDIVMODC
import Tests.Instr.Arith.LSHIFTDIVMODR
import Tests.Instr.Arith.LSHIFTDIVR
import Tests.Instr.Arith.LSHIFTMOD
import Tests.Instr.Arith.LSHIFTMODC
import Tests.Instr.Arith.LSHIFTMODR
import Tests.Instr.Arith.LSHIFT_HASH_ADDDIVMOD
import Tests.Instr.Arith.LSHIFT_HASH_ADDDIVMODC
import Tests.Instr.Arith.LSHIFT_HASH_ADDDIVMODR
import Tests.Instr.Arith.LSHIFT_HASH_DIV
import Tests.Instr.Arith.LSHIFT_HASH_DIVC
import Tests.Instr.Arith.LSHIFT_HASH_DIVMOD
import Tests.Instr.Arith.LSHIFT_HASH_DIVMODC
import Tests.Instr.Arith.LSHIFT_HASH_DIVMODR
import Tests.Instr.Arith.LSHIFT_HASH_DIVR
import Tests.Instr.Arith.LSHIFT_HASH_MOD
import Tests.Instr.Arith.LSHIFT_HASH_MODC
import Tests.Instr.Arith.LSHIFT_HASH_MODR
import Tests.Instr.Arith.LSHIFT_VAR
import Tests.Instr.Arith.MAX
import Tests.Instr.Arith.MIN
import Tests.Instr.Arith.MINMAX
import Tests.Instr.Arith.MOD
import Tests.Instr.Arith.MODC
import Tests.Instr.Arith.MODPOW2
import Tests.Instr.Arith.MODPOW2C
import Tests.Instr.Arith.MODPOW2C_HASH
import Tests.Instr.Arith.MODPOW2R
import Tests.Instr.Arith.MODPOW2R_HASH
import Tests.Instr.Arith.MODPOW2_HASH
import Tests.Instr.Arith.MODR
import Tests.Instr.Arith.MUL
import Tests.Instr.Arith.MULADDDIVMOD
import Tests.Instr.Arith.MULADDDIVMODC
import Tests.Instr.Arith.MULADDDIVMODR
import Tests.Instr.Arith.MULADDRSHIFTCMOD
import Tests.Instr.Arith.MULADDRSHIFTC_HASH_MOD
import Tests.Instr.Arith.MULADDRSHIFTMOD
import Tests.Instr.Arith.MULADDRSHIFTRMOD
import Tests.Instr.Arith.MULADDRSHIFTR_HASH_MOD
import Tests.Instr.Arith.MULADDRSHIFT_HASH_MOD
import Tests.Instr.Arith.MULDIV
import Tests.Instr.Arith.MULDIVC
import Tests.Instr.Arith.MULDIVMOD
import Tests.Instr.Arith.MULDIVMODC
import Tests.Instr.Arith.MULDIVMODR
import Tests.Instr.Arith.MULDIVR
import Tests.Instr.Arith.MULINT
import Tests.Instr.Arith.MULMOD
import Tests.Instr.Arith.MULMODC
import Tests.Instr.Arith.MULMODPOW2
import Tests.Instr.Arith.MULMODPOW2C
import Tests.Instr.Arith.MULMODPOW2C_HASH
import Tests.Instr.Arith.MULMODPOW2R
import Tests.Instr.Arith.MULMODPOW2R_HASH
import Tests.Instr.Arith.MULMODPOW2_HASH
import Tests.Instr.Arith.MULMODR
import Tests.Instr.Arith.MULRSHIFT
import Tests.Instr.Arith.MULRSHIFTC
import Tests.Instr.Arith.MULRSHIFTCMOD
import Tests.Instr.Arith.MULRSHIFTC_HASH
import Tests.Instr.Arith.MULRSHIFTC_HASH_MOD
import Tests.Instr.Arith.MULRSHIFTMOD
import Tests.Instr.Arith.MULRSHIFTR
import Tests.Instr.Arith.MULRSHIFTRMOD
import Tests.Instr.Arith.MULRSHIFTR_HASH
import Tests.Instr.Arith.MULRSHIFTR_HASH_MOD
import Tests.Instr.Arith.MULRSHIFT_HASH
import Tests.Instr.Arith.MULRSHIFT_HASH_MOD
import Tests.Instr.Arith.NEGATE
import Tests.Instr.Arith.NEQ
import Tests.Instr.Arith.NEQINT
import Tests.Instr.Arith.NOT
import Tests.Instr.Arith.OR
import Tests.Instr.Arith.POW2
import Tests.Instr.Arith.PUSHINT_16
import Tests.Instr.Arith.PUSHINT_4
import Tests.Instr.Arith.PUSHINT_8
import Tests.Instr.Arith.PUSHINT_LONG
import Tests.Instr.Arith.PUSHNAN
import Tests.Instr.Arith.PUSHNEGPOW2
import Tests.Instr.Arith.PUSHPOW2
import Tests.Instr.Arith.PUSHPOW2DEC
import Tests.Instr.Arith.QABS
import Tests.Instr.Arith.QADD
import Tests.Instr.Arith.QADDDIVMOD
import Tests.Instr.Arith.QADDDIVMODC
import Tests.Instr.Arith.QADDDIVMODR
import Tests.Instr.Arith.QADDINT
import Tests.Instr.Arith.QADDRSHIFTMOD
import Tests.Instr.Arith.QADDRSHIFTMODC
import Tests.Instr.Arith.QADDRSHIFTMODR
import Tests.Instr.Arith.QAND
import Tests.Instr.Arith.QBITSIZE
import Tests.Instr.Arith.QCMP
import Tests.Instr.Arith.QDEC
import Tests.Instr.Arith.QDIV
import Tests.Instr.Arith.QDIVC
import Tests.Instr.Arith.QDIVMOD
import Tests.Instr.Arith.QDIVMODC
import Tests.Instr.Arith.QDIVMODR
import Tests.Instr.Arith.QDIVR
import Tests.Instr.Arith.QEQINT
import Tests.Instr.Arith.QEQUAL
import Tests.Instr.Arith.QFITS
import Tests.Instr.Arith.QFITSX
import Tests.Instr.Arith.QGEQ
import Tests.Instr.Arith.QGREATER
import Tests.Instr.Arith.QGTINT
import Tests.Instr.Arith.QINC
import Tests.Instr.Arith.QLEQ
import Tests.Instr.Arith.QLESS
import Tests.Instr.Arith.QLESSINT
import Tests.Instr.Arith.QLSHIFT
import Tests.Instr.Arith.QLSHIFTADDDIVMOD
import Tests.Instr.Arith.QLSHIFTADDDIVMODC
import Tests.Instr.Arith.QLSHIFTADDDIVMODR
import Tests.Instr.Arith.QLSHIFTDIV
import Tests.Instr.Arith.QLSHIFTDIVC
import Tests.Instr.Arith.QLSHIFTDIVMOD
import Tests.Instr.Arith.QLSHIFTDIVMODC
import Tests.Instr.Arith.QLSHIFTDIVMODR
import Tests.Instr.Arith.QLSHIFTDIVR
import Tests.Instr.Arith.QLSHIFTMOD
import Tests.Instr.Arith.QLSHIFTMODC
import Tests.Instr.Arith.QLSHIFTMODR
import Tests.Instr.Arith.QLSHIFT_VAR
import Tests.Instr.Arith.QMAX
import Tests.Instr.Arith.QMIN
import Tests.Instr.Arith.QMINMAX
import Tests.Instr.Arith.QMOD
import Tests.Instr.Arith.QMODC
import Tests.Instr.Arith.QMODPOW2
import Tests.Instr.Arith.QMODPOW2C
import Tests.Instr.Arith.QMODPOW2R
import Tests.Instr.Arith.QMODR
import Tests.Instr.Arith.QMUL
import Tests.Instr.Arith.QMULADDDIVMOD
import Tests.Instr.Arith.QMULADDDIVMODC
import Tests.Instr.Arith.QMULADDDIVMODR
import Tests.Instr.Arith.QMULADDRSHIFTCMOD
import Tests.Instr.Arith.QMULADDRSHIFTMOD
import Tests.Instr.Arith.QMULADDRSHIFTRMOD
import Tests.Instr.Arith.QMULDIV
import Tests.Instr.Arith.QMULDIVC
import Tests.Instr.Arith.QMULDIVMOD
import Tests.Instr.Arith.QMULDIVMODC
import Tests.Instr.Arith.QMULDIVMODR
import Tests.Instr.Arith.QMULDIVR
import Tests.Instr.Arith.QMULINT
import Tests.Instr.Arith.QMULMOD
import Tests.Instr.Arith.QMULMODC
import Tests.Instr.Arith.QMULMODPOW2
import Tests.Instr.Arith.QMULMODPOW2C
import Tests.Instr.Arith.QMULMODPOW2R
import Tests.Instr.Arith.QMULMODR
import Tests.Instr.Arith.QMULRSHIFT
import Tests.Instr.Arith.QMULRSHIFTC
import Tests.Instr.Arith.QMULRSHIFTCMOD
import Tests.Instr.Arith.QMULRSHIFTMOD
import Tests.Instr.Arith.QMULRSHIFTR
import Tests.Instr.Arith.QMULRSHIFTRMOD
import Tests.Instr.Arith.QNEGATE
import Tests.Instr.Arith.QNEQ
import Tests.Instr.Arith.QNEQINT
import Tests.Instr.Arith.QNOT
import Tests.Instr.Arith.QOR
import Tests.Instr.Arith.QPOW2
import Tests.Instr.Arith.QRSHIFT
import Tests.Instr.Arith.QRSHIFTC
import Tests.Instr.Arith.QRSHIFTMOD
import Tests.Instr.Arith.QRSHIFTMODC
import Tests.Instr.Arith.QRSHIFTMODR
import Tests.Instr.Arith.QRSHIFTR
import Tests.Instr.Arith.QRSHIFT_ALT
import Tests.Instr.Arith.QRSHIFT_VAR
import Tests.Instr.Arith.QSGN
import Tests.Instr.Arith.QSUB
import Tests.Instr.Arith.QSUBR
import Tests.Instr.Arith.QUBITSIZE
import Tests.Instr.Arith.QUFITS
import Tests.Instr.Arith.QUFITSX
import Tests.Instr.Arith.QXOR
import Tests.Instr.Arith.RSHIFT
import Tests.Instr.Arith.RSHIFTC
import Tests.Instr.Arith.RSHIFTC_HASH
import Tests.Instr.Arith.RSHIFTC_HASH_MOD
import Tests.Instr.Arith.RSHIFTMOD
import Tests.Instr.Arith.RSHIFTMODC
import Tests.Instr.Arith.RSHIFTMODR
import Tests.Instr.Arith.RSHIFTR
import Tests.Instr.Arith.RSHIFTR_HASH
import Tests.Instr.Arith.RSHIFTR_HASH_MOD
import Tests.Instr.Arith.RSHIFT_ALT
import Tests.Instr.Arith.RSHIFT_HASH
import Tests.Instr.Arith.RSHIFT_HASH_MOD
import Tests.Instr.Arith.RSHIFT_VAR
import Tests.Instr.Arith.SGN
import Tests.Instr.Arith.SUB
import Tests.Instr.Arith.SUBR
import Tests.Instr.Arith.UBITSIZE
import Tests.Instr.Arith.UFITS
import Tests.Instr.Arith.UFITSX
import Tests.Instr.Arith.XOR
import Tests.Instr.Cell.BBITREFS
import Tests.Instr.Cell.BBITS
import Tests.Instr.Cell.BCHKBITREFS
import Tests.Instr.Cell.BCHKBITREFSQ
import Tests.Instr.Cell.BCHKBITS
import Tests.Instr.Cell.BCHKBITSQ
import Tests.Instr.Cell.BCHKBITSQ_VAR
import Tests.Instr.Cell.BCHKBITS_VAR
import Tests.Instr.Cell.BCHKREFS
import Tests.Instr.Cell.BCHKREFSQ
import Tests.Instr.Cell.BDEPTH
import Tests.Instr.Cell.BREFS
import Tests.Instr.Cell.BREMBITREFS
import Tests.Instr.Cell.BREMBITS
import Tests.Instr.Cell.BREMREFS
import Tests.Instr.Cell.BTOS
import Tests.Instr.Cell.CDEPTH
import Tests.Instr.Cell.CDEPTHI
import Tests.Instr.Cell.CDEPTHIX
import Tests.Instr.Cell.CHASHI
import Tests.Instr.Cell.CHASHIX
import Tests.Instr.Cell.CLEVEL
import Tests.Instr.Cell.CLEVELMASK
import Tests.Instr.Cell.CTOS
import Tests.Instr.Cell.ENDC
import Tests.Instr.Cell.ENDCST
import Tests.Instr.Cell.ENDS
import Tests.Instr.Cell.ENDXC
import Tests.Instr.Cell.LDGRAMS
import Tests.Instr.Cell.LDI
import Tests.Instr.Cell.LDILE4
import Tests.Instr.Cell.LDILE4Q
import Tests.Instr.Cell.LDILE8
import Tests.Instr.Cell.LDILE8Q
import Tests.Instr.Cell.LDIQ
import Tests.Instr.Cell.LDIX
import Tests.Instr.Cell.LDIXQ
import Tests.Instr.Cell.LDI_ALT
import Tests.Instr.Cell.LDMSGADDR
import Tests.Instr.Cell.LDMSGADDRQ
import Tests.Instr.Cell.LDONES
import Tests.Instr.Cell.LDOPTSTDADDR
import Tests.Instr.Cell.LDOPTSTDADDRQ
import Tests.Instr.Cell.LDREF
import Tests.Instr.Cell.LDREFRTOS
import Tests.Instr.Cell.LDSAME
import Tests.Instr.Cell.LDSLICE
import Tests.Instr.Cell.LDSLICEQ
import Tests.Instr.Cell.LDSLICEX
import Tests.Instr.Cell.LDSLICEXQ
import Tests.Instr.Cell.LDSLICE_ALT
import Tests.Instr.Cell.LDSTDADDR
import Tests.Instr.Cell.LDSTDADDRQ
import Tests.Instr.Cell.LDU
import Tests.Instr.Cell.LDULE4
import Tests.Instr.Cell.LDULE4Q
import Tests.Instr.Cell.LDULE8
import Tests.Instr.Cell.LDULE8Q
import Tests.Instr.Cell.LDUQ
import Tests.Instr.Cell.LDUX
import Tests.Instr.Cell.LDUXQ
import Tests.Instr.Cell.LDU_ALT
import Tests.Instr.Cell.LDVARINT16
import Tests.Instr.Cell.LDVARINT32
import Tests.Instr.Cell.LDVARUINT32
import Tests.Instr.Cell.LDZEROES
import Tests.Instr.Cell.NEWC
import Tests.Instr.Cell.PLDI
import Tests.Instr.Cell.PLDILE4
import Tests.Instr.Cell.PLDILE4Q
import Tests.Instr.Cell.PLDILE8
import Tests.Instr.Cell.PLDILE8Q
import Tests.Instr.Cell.PLDIQ
import Tests.Instr.Cell.PLDIX
import Tests.Instr.Cell.PLDIXQ
import Tests.Instr.Cell.PLDREFIDX
import Tests.Instr.Cell.PLDREFVAR
import Tests.Instr.Cell.PLDSLICE
import Tests.Instr.Cell.PLDSLICEQ
import Tests.Instr.Cell.PLDSLICEX
import Tests.Instr.Cell.PLDSLICEXQ
import Tests.Instr.Cell.PLDU
import Tests.Instr.Cell.PLDULE4
import Tests.Instr.Cell.PLDULE4Q
import Tests.Instr.Cell.PLDULE8
import Tests.Instr.Cell.PLDULE8Q
import Tests.Instr.Cell.PLDUQ
import Tests.Instr.Cell.PLDUX
import Tests.Instr.Cell.PLDUXQ
import Tests.Instr.Cell.PLDUZ
import Tests.Instr.Cell.PUSHCONT
import Tests.Instr.Cell.PUSHCONT_SHORT
import Tests.Instr.Cell.PUSHREF
import Tests.Instr.Cell.PUSHREFCONT
import Tests.Instr.Cell.PUSHREFSLICE
import Tests.Instr.Cell.PUSHSLICE
import Tests.Instr.Cell.PUSHSLICE_LONG
import Tests.Instr.Cell.PUSHSLICE_REFS
import Tests.Instr.Cell.SBITREFS
import Tests.Instr.Cell.SBITS
import Tests.Instr.Cell.SCHKBITREFS
import Tests.Instr.Cell.SCHKBITREFSQ
import Tests.Instr.Cell.SCHKBITS
import Tests.Instr.Cell.SCHKBITSQ
import Tests.Instr.Cell.SCHKREFS
import Tests.Instr.Cell.SCHKREFSQ
import Tests.Instr.Cell.SCUTFIRST
import Tests.Instr.Cell.SCUTLAST
import Tests.Instr.Cell.SDBEGINS
import Tests.Instr.Cell.SDBEGINSQ
import Tests.Instr.Cell.SDBEGINSX
import Tests.Instr.Cell.SDBEGINSXQ
import Tests.Instr.Cell.SDCNTLEAD0
import Tests.Instr.Cell.SDCNTLEAD1
import Tests.Instr.Cell.SDCNTTRAIL0
import Tests.Instr.Cell.SDCNTTRAIL1
import Tests.Instr.Cell.SDCUTFIRST
import Tests.Instr.Cell.SDCUTLAST
import Tests.Instr.Cell.SDEMPTY
import Tests.Instr.Cell.SDEPTH
import Tests.Instr.Cell.SDEQ
import Tests.Instr.Cell.SDFIRST
import Tests.Instr.Cell.SDLEXCMP
import Tests.Instr.Cell.SDPFX
import Tests.Instr.Cell.SDPFXREV
import Tests.Instr.Cell.SDPPFX
import Tests.Instr.Cell.SDPPFXREV
import Tests.Instr.Cell.SDPSFX
import Tests.Instr.Cell.SDPSFXREV
import Tests.Instr.Cell.SDSFX
import Tests.Instr.Cell.SDSFXREV
import Tests.Instr.Cell.SDSKIPFIRST
import Tests.Instr.Cell.SDSKIPLAST
import Tests.Instr.Cell.SDSUBSTR
import Tests.Instr.Cell.SEMPTY
import Tests.Instr.Cell.SPLIT
import Tests.Instr.Cell.SPLITQ
import Tests.Instr.Cell.SREFS
import Tests.Instr.Cell.SREMPTY
import Tests.Instr.Cell.SSKIPFIRST
import Tests.Instr.Cell.SSKIPLAST
import Tests.Instr.Cell.STB
import Tests.Instr.Cell.STBQ
import Tests.Instr.Cell.STBR
import Tests.Instr.Cell.STBREF
import Tests.Instr.Cell.STBREFQ
import Tests.Instr.Cell.STBREFR
import Tests.Instr.Cell.STBREFRQ
import Tests.Instr.Cell.STBRQ
import Tests.Instr.Cell.STGRAMS
import Tests.Instr.Cell.STI
import Tests.Instr.Cell.STILE4
import Tests.Instr.Cell.STILE8
import Tests.Instr.Cell.STIQ
import Tests.Instr.Cell.STIR
import Tests.Instr.Cell.STIRQ
import Tests.Instr.Cell.STIX
import Tests.Instr.Cell.STIXQ
import Tests.Instr.Cell.STIXR
import Tests.Instr.Cell.STIXRQ
import Tests.Instr.Cell.STI_ALT
import Tests.Instr.Cell.STONES
import Tests.Instr.Cell.STOPTSTDADDR
import Tests.Instr.Cell.STOPTSTDADDRQ
import Tests.Instr.Cell.STREF
import Tests.Instr.Cell.STREF2CONST
import Tests.Instr.Cell.STREFCONST
import Tests.Instr.Cell.STREFQ
import Tests.Instr.Cell.STREFR
import Tests.Instr.Cell.STREFRQ
import Tests.Instr.Cell.STREF_ALT
import Tests.Instr.Cell.STSAME
import Tests.Instr.Cell.STSLICE
import Tests.Instr.Cell.STSLICECONST
import Tests.Instr.Cell.STSLICEQ
import Tests.Instr.Cell.STSLICER
import Tests.Instr.Cell.STSLICERQ
import Tests.Instr.Cell.STSLICE_ALT
import Tests.Instr.Cell.STSTDADDR
import Tests.Instr.Cell.STSTDADDRQ
import Tests.Instr.Cell.STU
import Tests.Instr.Cell.STULE4
import Tests.Instr.Cell.STULE8
import Tests.Instr.Cell.STUQ
import Tests.Instr.Cell.STUR
import Tests.Instr.Cell.STURQ
import Tests.Instr.Cell.STUX
import Tests.Instr.Cell.STUXQ
import Tests.Instr.Cell.STUXR
import Tests.Instr.Cell.STUXRQ
import Tests.Instr.Cell.STU_ALT
import Tests.Instr.Cell.STVARINT16
import Tests.Instr.Cell.STVARINT32
import Tests.Instr.Cell.STVARUINT32
import Tests.Instr.Cell.STZEROES
import Tests.Instr.Cell.SUBSLICE
import Tests.Instr.Cell.XCTOS
import Tests.Instr.Cell.XLOAD
import Tests.Instr.Cell.XLOADQ
import Tests.Instr.Cont.AGAIN
import Tests.Instr.Cont.AGAINBRK
import Tests.Instr.Cont.AGAINEND
import Tests.Instr.Cont.AGAINENDBRK
import Tests.Instr.Cont.ATEXIT
import Tests.Instr.Cont.ATEXITALT
import Tests.Instr.Cont.BLESS
import Tests.Instr.Cont.BLESSARGS
import Tests.Instr.Cont.BLESSVARARGS
import Tests.Instr.Cont.BOOLAND
import Tests.Instr.Cont.BOOLEVAL
import Tests.Instr.Cont.BOOLOR
import Tests.Instr.Cont.CALLCC
import Tests.Instr.Cont.CALLCCARGS
import Tests.Instr.Cont.CALLCCVARARGS
import Tests.Instr.Cont.CALLDICT
import Tests.Instr.Cont.CALLDICT_LONG
import Tests.Instr.Cont.CALLREF
import Tests.Instr.Cont.CALLXARGS
import Tests.Instr.Cont.CALLXARGS_1
import Tests.Instr.Cont.CALLXVARARGS
import Tests.Instr.Cont.COMPOSBOTH
import Tests.Instr.Cont.CONDSEL
import Tests.Instr.Cont.CONDSELCHK
import Tests.Instr.Cont.EXECUTE
import Tests.Instr.Cont.IF
import Tests.Instr.Cont.IFBITJMP
import Tests.Instr.Cont.IFBITJMPREF
import Tests.Instr.Cont.IFELSE
import Tests.Instr.Cont.IFELSEREF
import Tests.Instr.Cont.IFJMP
import Tests.Instr.Cont.IFJMPREF
import Tests.Instr.Cont.IFNBITJMP
import Tests.Instr.Cont.IFNBITJMPREF
import Tests.Instr.Cont.IFNOT
import Tests.Instr.Cont.IFNOTJMP
import Tests.Instr.Cont.IFNOTJMPREF
import Tests.Instr.Cont.IFNOTREF
import Tests.Instr.Cont.IFNOTRET
import Tests.Instr.Cont.IFNOTRETALT
import Tests.Instr.Cont.IFREF
import Tests.Instr.Cont.IFREFELSE
import Tests.Instr.Cont.IFREFELSEREF
import Tests.Instr.Cont.IFRET
import Tests.Instr.Cont.IFRETALT
import Tests.Instr.Cont.INVERT
import Tests.Instr.Cont.JMPDICT
import Tests.Instr.Cont.JMPREF
import Tests.Instr.Cont.JMPREFDATA
import Tests.Instr.Cont.JMPX
import Tests.Instr.Cont.JMPXARGS
import Tests.Instr.Cont.JMPXDATA
import Tests.Instr.Cont.JMPXVARARGS
import Tests.Instr.Cont.POPCTR
import Tests.Instr.Cont.POPCTRX
import Tests.Instr.Cont.POPSAVE
import Tests.Instr.Cont.PREPAREDICT
import Tests.Instr.Cont.PUSHCTR
import Tests.Instr.Cont.PUSHCTRX
import Tests.Instr.Cont.REPEAT
import Tests.Instr.Cont.REPEATBRK
import Tests.Instr.Cont.REPEATEND
import Tests.Instr.Cont.REPEATENDBRK
import Tests.Instr.Cont.RET
import Tests.Instr.Cont.RETALT
import Tests.Instr.Cont.RETARGS
import Tests.Instr.Cont.RETBOOL
import Tests.Instr.Cont.RETDATA
import Tests.Instr.Cont.RETURNARGS
import Tests.Instr.Cont.RETURNVARARGS
import Tests.Instr.Cont.RETVARARGS
import Tests.Instr.Cont.RUNVM
import Tests.Instr.Cont.RUNVMX
import Tests.Instr.Cont.SAMEALT
import Tests.Instr.Cont.SAMEALTSAVE
import Tests.Instr.Cont.SAVEALTCTR
import Tests.Instr.Cont.SAVEBOTHCTR
import Tests.Instr.Cont.SAVECTR
import Tests.Instr.Cont.SETALTCTR
import Tests.Instr.Cont.SETCONTARGS
import Tests.Instr.Cont.SETCONTCTR
import Tests.Instr.Cont.SETCONTCTRMANY
import Tests.Instr.Cont.SETCONTCTRMANYX
import Tests.Instr.Cont.SETCONTCTRX
import Tests.Instr.Cont.SETCONTVARARGS
import Tests.Instr.Cont.SETEXITALT
import Tests.Instr.Cont.SETNUMVARARGS
import Tests.Instr.Cont.SETRETCTR
import Tests.Instr.Cont.THENRET
import Tests.Instr.Cont.THENRETALT
import Tests.Instr.Cont.UNTIL
import Tests.Instr.Cont.UNTILBRK
import Tests.Instr.Cont.UNTILEND
import Tests.Instr.Cont.UNTILENDBRK
import Tests.Instr.Cont.WHILE
import Tests.Instr.Cont.WHILEBRK
import Tests.Instr.Cont.WHILEEND
import Tests.Instr.Cont.WHILEENDBRK
import Tests.Instr.Crypto.BLS_AGGREGATE
import Tests.Instr.Crypto.BLS_AGGREGATEVERIFY
import Tests.Instr.Crypto.BLS_FASTAGGREGATEVERIFY
import Tests.Instr.Crypto.BLS_G1_ADD
import Tests.Instr.Crypto.BLS_G1_INGROUP
import Tests.Instr.Crypto.BLS_G1_ISZERO
import Tests.Instr.Crypto.BLS_G1_MUL
import Tests.Instr.Crypto.BLS_G1_MULTIEXP
import Tests.Instr.Crypto.BLS_G1_NEG
import Tests.Instr.Crypto.BLS_G1_SUB
import Tests.Instr.Crypto.BLS_G1_ZERO
import Tests.Instr.Crypto.BLS_G2_ADD
import Tests.Instr.Crypto.BLS_G2_INGROUP
import Tests.Instr.Crypto.BLS_G2_ISZERO
import Tests.Instr.Crypto.BLS_G2_MUL
import Tests.Instr.Crypto.BLS_G2_MULTIEXP
import Tests.Instr.Crypto.BLS_G2_NEG
import Tests.Instr.Crypto.BLS_G2_SUB
import Tests.Instr.Crypto.BLS_G2_ZERO
import Tests.Instr.Crypto.BLS_MAP_TO_G1
import Tests.Instr.Crypto.BLS_MAP_TO_G2
import Tests.Instr.Crypto.BLS_PAIRING
import Tests.Instr.Crypto.BLS_PUSHR
import Tests.Instr.Crypto.BLS_VERIFY
import Tests.Instr.Crypto.CHKSIGNS
import Tests.Instr.Crypto.CHKSIGNU
import Tests.Instr.Crypto.ECRECOVER
import Tests.Instr.Crypto.HASHBU
import Tests.Instr.Crypto.HASHCU
import Tests.Instr.Crypto.HASHEXT
import Tests.Instr.Crypto.HASHEXTA
import Tests.Instr.Crypto.HASHEXTAR
import Tests.Instr.Crypto.HASHEXTR
import Tests.Instr.Crypto.HASHSU
import Tests.Instr.Crypto.P256_CHKSIGNS
import Tests.Instr.Crypto.P256_CHKSIGNU
import Tests.Instr.Crypto.RIST255_ADD
import Tests.Instr.Crypto.RIST255_FROMHASH
import Tests.Instr.Crypto.RIST255_MUL
import Tests.Instr.Crypto.RIST255_MULBASE
import Tests.Instr.Crypto.RIST255_PUSHL
import Tests.Instr.Crypto.RIST255_QADD
import Tests.Instr.Crypto.RIST255_QMUL
import Tests.Instr.Crypto.RIST255_QMULBASE
import Tests.Instr.Crypto.RIST255_QSUB
import Tests.Instr.Crypto.RIST255_QVALIDATE
import Tests.Instr.Crypto.RIST255_SUB
import Tests.Instr.Crypto.RIST255_VALIDATE
import Tests.Instr.Crypto.SECP256K1_XONLY_PUBKEY_TWEAK_ADD
import Tests.Instr.Crypto.SHA256U
import Tests.Instr.Debug.DEBUG
import Tests.Instr.Debug.DEBUGSTR
import Tests.Instr.Debug.DEBUG_1
import Tests.Instr.Debug.DEBUG_2
import Tests.Instr.Debug.DUMP
import Tests.Instr.Debug.DUMPSTK
import Tests.Instr.Debug.EXTCALL
import Tests.Instr.Debug.STRDUMP
import Tests.Instr.Dict.DICTADD
import Tests.Instr.Dict.DICTADDB
import Tests.Instr.Dict.DICTADDGET
import Tests.Instr.Dict.DICTADDGETB
import Tests.Instr.Dict.DICTADDGETREF
import Tests.Instr.Dict.DICTADDREF
import Tests.Instr.Dict.DICTDEL
import Tests.Instr.Dict.DICTDELGET
import Tests.Instr.Dict.DICTDELGETREF
import Tests.Instr.Dict.DICTGET
import Tests.Instr.Dict.DICTGETNEXT
import Tests.Instr.Dict.DICTGETNEXTEQ
import Tests.Instr.Dict.DICTGETOPTREF
import Tests.Instr.Dict.DICTGETPREV
import Tests.Instr.Dict.DICTGETPREVEQ
import Tests.Instr.Dict.DICTGETREF
import Tests.Instr.Dict.DICTIADD
import Tests.Instr.Dict.DICTIADDB
import Tests.Instr.Dict.DICTIADDGET
import Tests.Instr.Dict.DICTIADDGETB
import Tests.Instr.Dict.DICTIADDGETREF
import Tests.Instr.Dict.DICTIADDREF
import Tests.Instr.Dict.DICTIDEL
import Tests.Instr.Dict.DICTIDELGET
import Tests.Instr.Dict.DICTIDELGETREF
import Tests.Instr.Dict.DICTIGET
import Tests.Instr.Dict.DICTIGETEXEC
import Tests.Instr.Dict.DICTIGETEXECZ
import Tests.Instr.Dict.DICTIGETJMP
import Tests.Instr.Dict.DICTIGETJMPZ
import Tests.Instr.Dict.DICTIGETNEXT
import Tests.Instr.Dict.DICTIGETNEXTEQ
import Tests.Instr.Dict.DICTIGETOPTREF
import Tests.Instr.Dict.DICTIGETPREV
import Tests.Instr.Dict.DICTIGETPREVEQ
import Tests.Instr.Dict.DICTIGETREF
import Tests.Instr.Dict.DICTIMAX
import Tests.Instr.Dict.DICTIMAXREF
import Tests.Instr.Dict.DICTIMIN
import Tests.Instr.Dict.DICTIMINREF
import Tests.Instr.Dict.DICTIREMMAX
import Tests.Instr.Dict.DICTIREMMAXREF
import Tests.Instr.Dict.DICTIREMMIN
import Tests.Instr.Dict.DICTIREMMINREF
import Tests.Instr.Dict.DICTIREPLACE
import Tests.Instr.Dict.DICTIREPLACEB
import Tests.Instr.Dict.DICTIREPLACEGET
import Tests.Instr.Dict.DICTIREPLACEGETB
import Tests.Instr.Dict.DICTIREPLACEGETREF
import Tests.Instr.Dict.DICTIREPLACEREF
import Tests.Instr.Dict.DICTISET
import Tests.Instr.Dict.DICTISETB
import Tests.Instr.Dict.DICTISETGET
import Tests.Instr.Dict.DICTISETGETB
import Tests.Instr.Dict.DICTISETGETOPTREF
import Tests.Instr.Dict.DICTISETGETREF
import Tests.Instr.Dict.DICTISETREF
import Tests.Instr.Dict.DICTMAX
import Tests.Instr.Dict.DICTMAXREF
import Tests.Instr.Dict.DICTMIN
import Tests.Instr.Dict.DICTMINREF
import Tests.Instr.Dict.DICTPUSHCONST
import Tests.Instr.Dict.DICTREMMAX
import Tests.Instr.Dict.DICTREMMAXREF
import Tests.Instr.Dict.DICTREMMIN
import Tests.Instr.Dict.DICTREMMINREF
import Tests.Instr.Dict.DICTREPLACE
import Tests.Instr.Dict.DICTREPLACEB
import Tests.Instr.Dict.DICTREPLACEGET
import Tests.Instr.Dict.DICTREPLACEGETB
import Tests.Instr.Dict.DICTREPLACEGETREF
import Tests.Instr.Dict.DICTREPLACEREF
import Tests.Instr.Dict.DICTSET
import Tests.Instr.Dict.DICTSETB
import Tests.Instr.Dict.DICTSETGET
import Tests.Instr.Dict.DICTSETGETB
import Tests.Instr.Dict.DICTSETGETOPTREF
import Tests.Instr.Dict.DICTSETGETREF
import Tests.Instr.Dict.DICTSETREF
import Tests.Instr.Dict.DICTUADD
import Tests.Instr.Dict.DICTUADDB
import Tests.Instr.Dict.DICTUADDGET
import Tests.Instr.Dict.DICTUADDGETB
import Tests.Instr.Dict.DICTUADDGETREF
import Tests.Instr.Dict.DICTUADDREF
import Tests.Instr.Dict.DICTUDEL
import Tests.Instr.Dict.DICTUDELGET
import Tests.Instr.Dict.DICTUDELGETREF
import Tests.Instr.Dict.DICTUGET
import Tests.Instr.Dict.DICTUGETEXEC
import Tests.Instr.Dict.DICTUGETEXECZ
import Tests.Instr.Dict.DICTUGETJMP
import Tests.Instr.Dict.DICTUGETJMPZ
import Tests.Instr.Dict.DICTUGETNEXT
import Tests.Instr.Dict.DICTUGETNEXTEQ
import Tests.Instr.Dict.DICTUGETOPTREF
import Tests.Instr.Dict.DICTUGETPREV
import Tests.Instr.Dict.DICTUGETPREVEQ
import Tests.Instr.Dict.DICTUGETREF
import Tests.Instr.Dict.DICTUMAX
import Tests.Instr.Dict.DICTUMAXREF
import Tests.Instr.Dict.DICTUMIN
import Tests.Instr.Dict.DICTUMINREF
import Tests.Instr.Dict.DICTUREMMAX
import Tests.Instr.Dict.DICTUREMMAXREF
import Tests.Instr.Dict.DICTUREMMIN
import Tests.Instr.Dict.DICTUREMMINREF
import Tests.Instr.Dict.DICTUREPLACE
import Tests.Instr.Dict.DICTUREPLACEB
import Tests.Instr.Dict.DICTUREPLACEGET
import Tests.Instr.Dict.DICTUREPLACEGETB
import Tests.Instr.Dict.DICTUREPLACEGETREF
import Tests.Instr.Dict.DICTUREPLACEREF
import Tests.Instr.Dict.DICTUSET
import Tests.Instr.Dict.DICTUSETB
import Tests.Instr.Dict.DICTUSETGET
import Tests.Instr.Dict.DICTUSETGETB
import Tests.Instr.Dict.DICTUSETGETOPTREF
import Tests.Instr.Dict.DICTUSETGETREF
import Tests.Instr.Dict.DICTUSETREF
import Tests.Instr.Dict.LDDICT
import Tests.Instr.Dict.LDDICTQ
import Tests.Instr.Dict.LDDICTS
import Tests.Instr.Dict.PFXDICTADD
import Tests.Instr.Dict.PFXDICTDEL
import Tests.Instr.Dict.PFXDICTGET
import Tests.Instr.Dict.PFXDICTGETEXEC
import Tests.Instr.Dict.PFXDICTGETJMP
import Tests.Instr.Dict.PFXDICTGETQ
import Tests.Instr.Dict.PFXDICTREPLACE
import Tests.Instr.Dict.PFXDICTSET
import Tests.Instr.Dict.PFXDICTSWITCH
import Tests.Instr.Dict.PLDDICT
import Tests.Instr.Dict.PLDDICTQ
import Tests.Instr.Dict.PLDDICTS
import Tests.Instr.Dict.SKIPDICT
import Tests.Instr.Dict.STDICT
import Tests.Instr.Dict.SUBDICTGET
import Tests.Instr.Dict.SUBDICTIGET
import Tests.Instr.Dict.SUBDICTIRPGET
import Tests.Instr.Dict.SUBDICTRPGET
import Tests.Instr.Dict.SUBDICTUGET
import Tests.Instr.Dict.SUBDICTURPGET
import Tests.Instr.Exception.THROW
import Tests.Instr.Exception.THROWANY
import Tests.Instr.Exception.THROWANYIF
import Tests.Instr.Exception.THROWANYIFNOT
import Tests.Instr.Exception.THROWARG
import Tests.Instr.Exception.THROWARGANY
import Tests.Instr.Exception.THROWARGANYIF
import Tests.Instr.Exception.THROWARGANYIFNOT
import Tests.Instr.Exception.THROWARGIF
import Tests.Instr.Exception.THROWARGIFNOT
import Tests.Instr.Exception.THROWIF
import Tests.Instr.Exception.THROWIFNOT
import Tests.Instr.Exception.THROWIFNOT_SHORT
import Tests.Instr.Exception.THROWIF_SHORT
import Tests.Instr.Exception.THROW_SHORT
import Tests.Instr.Exception.TRY
import Tests.Instr.Exception.TRYARGS
import Tests.Instr.Flow.SETCP
import Tests.Instr.Flow.SETCPX
import Tests.Instr.Flow.SETCP_SHORT
import Tests.Instr.Misc.CDATASIZE
import Tests.Instr.Misc.CDATASIZEQ
import Tests.Instr.Misc.SDATASIZE
import Tests.Instr.Misc.SDATASIZEQ
import Tests.Instr.Msg.CHANGELIB
import Tests.Instr.Msg.RAWRESERVE
import Tests.Instr.Msg.RAWRESERVEX
import Tests.Instr.Msg.SENDMSG
import Tests.Instr.Msg.SENDRAWMSG
import Tests.Instr.Msg.SETCODE
import Tests.Instr.Msg.SETLIBCODE
import Tests.Instr.Stack.BLKDROP
import Tests.Instr.Stack.BLKDROP2
import Tests.Instr.Stack.BLKPUSH
import Tests.Instr.Stack.BLKSWAP
import Tests.Instr.Stack.BLKSWX
import Tests.Instr.Stack.CHKDEPTH
import Tests.Instr.Stack.DEPTH
import Tests.Instr.Stack.DROP
import Tests.Instr.Stack.DROPX
import Tests.Instr.Stack.DUP
import Tests.Instr.Stack.NIP
import Tests.Instr.Stack.NOP
import Tests.Instr.Stack.ONLYTOPX
import Tests.Instr.Stack.ONLYX
import Tests.Instr.Stack.OP_2DROP
import Tests.Instr.Stack.OP_2DUP
import Tests.Instr.Stack.OP_2OVER
import Tests.Instr.Stack.OP_2SWAP
import Tests.Instr.Stack.OVER
import Tests.Instr.Stack.PICK
import Tests.Instr.Stack.POP
import Tests.Instr.Stack.POP_LONG
import Tests.Instr.Stack.PU2XC
import Tests.Instr.Stack.PUSH
import Tests.Instr.Stack.PUSH2
import Tests.Instr.Stack.PUSH3
import Tests.Instr.Stack.PUSH_LONG
import Tests.Instr.Stack.PUXC
import Tests.Instr.Stack.PUXC2
import Tests.Instr.Stack.PUXCPU
import Tests.Instr.Stack.REVERSE
import Tests.Instr.Stack.REVX
import Tests.Instr.Stack.ROLL
import Tests.Instr.Stack.ROLLREV
import Tests.Instr.Stack.ROT
import Tests.Instr.Stack.ROTREV
import Tests.Instr.Stack.SWAP
import Tests.Instr.Stack.TUCK
import Tests.Instr.Stack.XC2PU
import Tests.Instr.Stack.XCHG2
import Tests.Instr.Stack.XCHG3
import Tests.Instr.Stack.XCHG3_ALT
import Tests.Instr.Stack.XCHGX
import Tests.Instr.Stack.XCHG_0I
import Tests.Instr.Stack.XCHG_0I_LONG
import Tests.Instr.Stack.XCHG_1I
import Tests.Instr.Stack.XCHG_IJ
import Tests.Instr.Stack.XCPU
import Tests.Instr.Stack.XCPU2
import Tests.Instr.Stack.XCPUXC
import Tests.Instr.TonEnv.ACCEPT
import Tests.Instr.TonEnv.ADDRAND
import Tests.Instr.TonEnv.BALANCE
import Tests.Instr.TonEnv.BLOCKLT
import Tests.Instr.TonEnv.COMMIT
import Tests.Instr.TonEnv.CONFIGDICT
import Tests.Instr.TonEnv.CONFIGOPTPARAM
import Tests.Instr.TonEnv.CONFIGPARAM
import Tests.Instr.TonEnv.CONFIGROOT
import Tests.Instr.TonEnv.DUEPAYMENT
import Tests.Instr.TonEnv.GASCONSUMED
import Tests.Instr.TonEnv.GETFORWARDFEE
import Tests.Instr.TonEnv.GETFORWARDFEESIMPLE
import Tests.Instr.TonEnv.GETGASFEE
import Tests.Instr.TonEnv.GETGASFEESIMPLE
import Tests.Instr.TonEnv.GETGLOB
import Tests.Instr.TonEnv.GETGLOBVAR
import Tests.Instr.TonEnv.GETORIGINALFWDFEE
import Tests.Instr.TonEnv.GETPARAM
import Tests.Instr.TonEnv.GETPARAMLONG
import Tests.Instr.TonEnv.GETPARAMLONG2
import Tests.Instr.TonEnv.GETPRECOMPILEDGAS
import Tests.Instr.TonEnv.GETSTORAGEFEE
import Tests.Instr.TonEnv.GLOBALID
import Tests.Instr.TonEnv.INCOMINGVALUE
import Tests.Instr.TonEnv.INMSGPARAM
import Tests.Instr.TonEnv.INMSGPARAMS
import Tests.Instr.TonEnv.INMSG_BOUNCE
import Tests.Instr.TonEnv.INMSG_BOUNCED
import Tests.Instr.TonEnv.INMSG_FWDFEE
import Tests.Instr.TonEnv.INMSG_LT
import Tests.Instr.TonEnv.INMSG_ORIGVALUE
import Tests.Instr.TonEnv.INMSG_SRC
import Tests.Instr.TonEnv.INMSG_STATEINIT
import Tests.Instr.TonEnv.INMSG_UTIME
import Tests.Instr.TonEnv.INMSG_VALUE
import Tests.Instr.TonEnv.INMSG_VALUEEXTRA
import Tests.Instr.TonEnv.LTIME
import Tests.Instr.TonEnv.MYADDR
import Tests.Instr.TonEnv.MYCODE
import Tests.Instr.TonEnv.NOW
import Tests.Instr.TonEnv.PARSEMSGADDR
import Tests.Instr.TonEnv.PARSEMSGADDRQ
import Tests.Instr.TonEnv.PREVBLOCKSINFOTUPLE
import Tests.Instr.TonEnv.PREVKEYBLOCK
import Tests.Instr.TonEnv.PREVMCBLOCKS
import Tests.Instr.TonEnv.PREVMCBLOCKS_100
import Tests.Instr.TonEnv.RAND
import Tests.Instr.TonEnv.RANDSEED
import Tests.Instr.TonEnv.RANDU256
import Tests.Instr.TonEnv.REWRITESTDADDR
import Tests.Instr.TonEnv.REWRITESTDADDRQ
import Tests.Instr.TonEnv.REWRITEVARADDR
import Tests.Instr.TonEnv.REWRITEVARADDRQ
import Tests.Instr.TonEnv.SETGASLIMIT
import Tests.Instr.TonEnv.SETGLOB
import Tests.Instr.TonEnv.SETGLOBVAR
import Tests.Instr.TonEnv.SETRAND
import Tests.Instr.TonEnv.STORAGEFEES
import Tests.Instr.TonEnv.UNPACKEDCONFIGTUPLE
import Tests.Instr.Tuple.EXPLODE
import Tests.Instr.Tuple.EXPLODEVAR
import Tests.Instr.Tuple.INDEX
import Tests.Instr.Tuple.INDEX2
import Tests.Instr.Tuple.INDEX3
import Tests.Instr.Tuple.INDEXQ
import Tests.Instr.Tuple.INDEXVAR
import Tests.Instr.Tuple.INDEXVARQ
import Tests.Instr.Tuple.ISNULL
import Tests.Instr.Tuple.ISTUPLE
import Tests.Instr.Tuple.LAST
import Tests.Instr.Tuple.NULLROTRIF
import Tests.Instr.Tuple.NULLROTRIF2
import Tests.Instr.Tuple.NULLROTRIFNOT
import Tests.Instr.Tuple.NULLROTRIFNOT2
import Tests.Instr.Tuple.NULLSWAPIF
import Tests.Instr.Tuple.NULLSWAPIF2
import Tests.Instr.Tuple.NULLSWAPIFNOT
import Tests.Instr.Tuple.NULLSWAPIFNOT2
import Tests.Instr.Tuple.PUSHNULL
import Tests.Instr.Tuple.QTLEN
import Tests.Instr.Tuple.SETINDEX
import Tests.Instr.Tuple.SETINDEXQ
import Tests.Instr.Tuple.SETINDEXVAR
import Tests.Instr.Tuple.SETINDEXVARQ
import Tests.Instr.Tuple.TLEN
import Tests.Instr.Tuple.TPOP
import Tests.Instr.Tuple.TPUSH
import Tests.Instr.Tuple.TUPLE
import Tests.Instr.Tuple.TUPLEVAR
import Tests.Instr.Tuple.UNPACKFIRST
import Tests.Instr.Tuple.UNPACKFIRSTVAR
import Tests.Instr.Tuple.UNTUPLE
import Tests.Instr.Tuple.UNTUPLEVAR

open Tests

namespace Tests

def allInstrSuites : Array InstrSuite :=
  #[
    Tests.Instr.Arith.ABS.suite,
    Tests.Instr.Arith.ADD.suite,
    Tests.Instr.Arith.ADDDIVMOD.suite,
    Tests.Instr.Arith.ADDDIVMODC.suite,
    Tests.Instr.Arith.ADDDIVMODR.suite,
    Tests.Instr.Arith.ADDINT.suite,
    Tests.Instr.Arith.ADDRSHIFTC_HASH_MOD.suite,
    Tests.Instr.Arith.ADDRSHIFTMOD.suite,
    Tests.Instr.Arith.ADDRSHIFTMODC.suite,
    Tests.Instr.Arith.ADDRSHIFTMODR.suite,
    Tests.Instr.Arith.ADDRSHIFTR_HASH_MOD.suite,
    Tests.Instr.Arith.ADDRSHIFT_HASH_MOD.suite,
    Tests.Instr.Arith.AND.suite,
    Tests.Instr.Arith.BITSIZE.suite,
    Tests.Instr.Arith.CHKNAN.suite,
    Tests.Instr.Arith.CMP.suite,
    Tests.Instr.Arith.DEC.suite,
    Tests.Instr.Arith.DIV.suite,
    Tests.Instr.Arith.DIVC.suite,
    Tests.Instr.Arith.DIVMOD.suite,
    Tests.Instr.Arith.DIVMODC.suite,
    Tests.Instr.Arith.DIVMODR.suite,
    Tests.Instr.Arith.DIVR.suite,
    Tests.Instr.Arith.EQINT.suite,
    Tests.Instr.Arith.EQUAL.suite,
    Tests.Instr.Arith.FITS.suite,
    Tests.Instr.Arith.FITSX.suite,
    Tests.Instr.Arith.GEQ.suite,
    Tests.Instr.Arith.GREATER.suite,
    Tests.Instr.Arith.GTINT.suite,
    Tests.Instr.Arith.INC.suite,
    Tests.Instr.Arith.ISNAN.suite,
    Tests.Instr.Arith.LEQ.suite,
    Tests.Instr.Arith.LESS.suite,
    Tests.Instr.Arith.LESSINT.suite,
    Tests.Instr.Arith.LSHIFT.suite,
    Tests.Instr.Arith.LSHIFTADDDIVMOD.suite,
    Tests.Instr.Arith.LSHIFTADDDIVMODC.suite,
    Tests.Instr.Arith.LSHIFTADDDIVMODR.suite,
    Tests.Instr.Arith.LSHIFTDIV.suite,
    Tests.Instr.Arith.LSHIFTDIVC.suite,
    Tests.Instr.Arith.LSHIFTDIVMOD.suite,
    Tests.Instr.Arith.LSHIFTDIVMODC.suite,
    Tests.Instr.Arith.LSHIFTDIVMODR.suite,
    Tests.Instr.Arith.LSHIFTDIVR.suite,
    Tests.Instr.Arith.LSHIFTMOD.suite,
    Tests.Instr.Arith.LSHIFTMODC.suite,
    Tests.Instr.Arith.LSHIFTMODR.suite,
    Tests.Instr.Arith.LSHIFT_HASH_ADDDIVMOD.suite,
    Tests.Instr.Arith.LSHIFT_HASH_ADDDIVMODC.suite,
    Tests.Instr.Arith.LSHIFT_HASH_ADDDIVMODR.suite,
    Tests.Instr.Arith.LSHIFT_HASH_DIV.suite,
    Tests.Instr.Arith.LSHIFT_HASH_DIVC.suite,
    Tests.Instr.Arith.LSHIFT_HASH_DIVMOD.suite,
    Tests.Instr.Arith.LSHIFT_HASH_DIVMODC.suite,
    Tests.Instr.Arith.LSHIFT_HASH_DIVMODR.suite,
    Tests.Instr.Arith.LSHIFT_HASH_DIVR.suite,
    Tests.Instr.Arith.LSHIFT_HASH_MOD.suite,
    Tests.Instr.Arith.LSHIFT_HASH_MODC.suite,
    Tests.Instr.Arith.LSHIFT_HASH_MODR.suite,
    Tests.Instr.Arith.LSHIFT_VAR.suite,
    Tests.Instr.Arith.MAX.suite,
    Tests.Instr.Arith.MIN.suite,
    Tests.Instr.Arith.MINMAX.suite,
    Tests.Instr.Arith.MOD.suite,
    Tests.Instr.Arith.MODC.suite,
    Tests.Instr.Arith.MODPOW2.suite,
    Tests.Instr.Arith.MODPOW2C.suite,
    Tests.Instr.Arith.MODPOW2C_HASH.suite,
    Tests.Instr.Arith.MODPOW2R.suite,
    Tests.Instr.Arith.MODPOW2R_HASH.suite,
    Tests.Instr.Arith.MODPOW2_HASH.suite,
    Tests.Instr.Arith.MODR.suite,
    Tests.Instr.Arith.MUL.suite,
    Tests.Instr.Arith.MULADDDIVMOD.suite,
    Tests.Instr.Arith.MULADDDIVMODC.suite,
    Tests.Instr.Arith.MULADDDIVMODR.suite,
    Tests.Instr.Arith.MULADDRSHIFTCMOD.suite,
    Tests.Instr.Arith.MULADDRSHIFTC_HASH_MOD.suite,
    Tests.Instr.Arith.MULADDRSHIFTMOD.suite,
    Tests.Instr.Arith.MULADDRSHIFTRMOD.suite,
    Tests.Instr.Arith.MULADDRSHIFTR_HASH_MOD.suite,
    Tests.Instr.Arith.MULADDRSHIFT_HASH_MOD.suite,
    Tests.Instr.Arith.MULDIV.suite,
    Tests.Instr.Arith.MULDIVC.suite,
    Tests.Instr.Arith.MULDIVMOD.suite,
    Tests.Instr.Arith.MULDIVMODC.suite,
    Tests.Instr.Arith.MULDIVMODR.suite,
    Tests.Instr.Arith.MULDIVR.suite,
    Tests.Instr.Arith.MULINT.suite,
    Tests.Instr.Arith.MULMOD.suite,
    Tests.Instr.Arith.MULMODC.suite,
    Tests.Instr.Arith.MULMODPOW2.suite,
    Tests.Instr.Arith.MULMODPOW2C.suite,
    Tests.Instr.Arith.MULMODPOW2C_HASH.suite,
    Tests.Instr.Arith.MULMODPOW2R.suite,
    Tests.Instr.Arith.MULMODPOW2R_HASH.suite,
    Tests.Instr.Arith.MULMODPOW2_HASH.suite,
    Tests.Instr.Arith.MULMODR.suite,
    Tests.Instr.Arith.MULRSHIFT.suite,
    Tests.Instr.Arith.MULRSHIFTC.suite,
    Tests.Instr.Arith.MULRSHIFTCMOD.suite,
    Tests.Instr.Arith.MULRSHIFTC_HASH.suite,
    Tests.Instr.Arith.MULRSHIFTC_HASH_MOD.suite,
    Tests.Instr.Arith.MULRSHIFTMOD.suite,
    Tests.Instr.Arith.MULRSHIFTR.suite,
    Tests.Instr.Arith.MULRSHIFTRMOD.suite,
    Tests.Instr.Arith.MULRSHIFTR_HASH.suite,
    Tests.Instr.Arith.MULRSHIFTR_HASH_MOD.suite,
    Tests.Instr.Arith.MULRSHIFT_HASH.suite,
    Tests.Instr.Arith.MULRSHIFT_HASH_MOD.suite,
    Tests.Instr.Arith.NEGATE.suite,
    Tests.Instr.Arith.NEQ.suite,
    Tests.Instr.Arith.NEQINT.suite,
    Tests.Instr.Arith.NOT.suite,
    Tests.Instr.Arith.OR.suite,
    Tests.Instr.Arith.POW2.suite,
    Tests.Instr.Arith.PUSHINT_16.suite,
    Tests.Instr.Arith.PUSHINT_4.suite,
    Tests.Instr.Arith.PUSHINT_8.suite,
    Tests.Instr.Arith.PUSHINT_LONG.suite,
    Tests.Instr.Arith.PUSHNAN.suite,
    Tests.Instr.Arith.PUSHNEGPOW2.suite,
    Tests.Instr.Arith.PUSHPOW2.suite,
    Tests.Instr.Arith.PUSHPOW2DEC.suite,
    Tests.Instr.Arith.QABS.suite,
    Tests.Instr.Arith.QADD.suite,
    Tests.Instr.Arith.QADDDIVMOD.suite,
    Tests.Instr.Arith.QADDDIVMODC.suite,
    Tests.Instr.Arith.QADDDIVMODR.suite,
    Tests.Instr.Arith.QADDINT.suite,
    Tests.Instr.Arith.QADDRSHIFTMOD.suite,
    Tests.Instr.Arith.QADDRSHIFTMODC.suite,
    Tests.Instr.Arith.QADDRSHIFTMODR.suite,
    Tests.Instr.Arith.QAND.suite,
    Tests.Instr.Arith.QBITSIZE.suite,
    Tests.Instr.Arith.QCMP.suite,
    Tests.Instr.Arith.QDEC.suite,
    Tests.Instr.Arith.QDIV.suite,
    Tests.Instr.Arith.QDIVC.suite,
    Tests.Instr.Arith.QDIVMOD.suite,
    Tests.Instr.Arith.QDIVMODC.suite,
    Tests.Instr.Arith.QDIVMODR.suite,
    Tests.Instr.Arith.QDIVR.suite,
    Tests.Instr.Arith.QEQINT.suite,
    Tests.Instr.Arith.QEQUAL.suite,
    Tests.Instr.Arith.QFITS.suite,
    Tests.Instr.Arith.QFITSX.suite,
    Tests.Instr.Arith.QGEQ.suite,
    Tests.Instr.Arith.QGREATER.suite,
    Tests.Instr.Arith.QGTINT.suite,
    Tests.Instr.Arith.QINC.suite,
    Tests.Instr.Arith.QLEQ.suite,
    Tests.Instr.Arith.QLESS.suite,
    Tests.Instr.Arith.QLESSINT.suite,
    Tests.Instr.Arith.QLSHIFT.suite,
    Tests.Instr.Arith.QLSHIFTADDDIVMOD.suite,
    Tests.Instr.Arith.QLSHIFTADDDIVMODC.suite,
    Tests.Instr.Arith.QLSHIFTADDDIVMODR.suite,
    Tests.Instr.Arith.QLSHIFTDIV.suite,
    Tests.Instr.Arith.QLSHIFTDIVC.suite,
    Tests.Instr.Arith.QLSHIFTDIVMOD.suite,
    Tests.Instr.Arith.QLSHIFTDIVMODC.suite,
    Tests.Instr.Arith.QLSHIFTDIVMODR.suite,
    Tests.Instr.Arith.QLSHIFTDIVR.suite,
    Tests.Instr.Arith.QLSHIFTMOD.suite,
    Tests.Instr.Arith.QLSHIFTMODC.suite,
    Tests.Instr.Arith.QLSHIFTMODR.suite,
    Tests.Instr.Arith.QLSHIFT_VAR.suite,
    Tests.Instr.Arith.QMAX.suite,
    Tests.Instr.Arith.QMIN.suite,
    Tests.Instr.Arith.QMINMAX.suite,
    Tests.Instr.Arith.QMOD.suite,
    Tests.Instr.Arith.QMODC.suite,
    Tests.Instr.Arith.QMODPOW2.suite,
    Tests.Instr.Arith.QMODPOW2C.suite,
    Tests.Instr.Arith.QMODPOW2R.suite,
    Tests.Instr.Arith.QMODR.suite,
    Tests.Instr.Arith.QMUL.suite,
    Tests.Instr.Arith.QMULADDDIVMOD.suite,
    Tests.Instr.Arith.QMULADDDIVMODC.suite,
    Tests.Instr.Arith.QMULADDDIVMODR.suite,
    Tests.Instr.Arith.QMULADDRSHIFTCMOD.suite,
    Tests.Instr.Arith.QMULADDRSHIFTMOD.suite,
    Tests.Instr.Arith.QMULADDRSHIFTRMOD.suite,
    Tests.Instr.Arith.QMULDIV.suite,
    Tests.Instr.Arith.QMULDIVC.suite,
    Tests.Instr.Arith.QMULDIVMOD.suite,
    Tests.Instr.Arith.QMULDIVMODC.suite,
    Tests.Instr.Arith.QMULDIVMODR.suite,
    Tests.Instr.Arith.QMULDIVR.suite,
    Tests.Instr.Arith.QMULINT.suite,
    Tests.Instr.Arith.QMULMOD.suite,
    Tests.Instr.Arith.QMULMODC.suite,
    Tests.Instr.Arith.QMULMODPOW2.suite,
    Tests.Instr.Arith.QMULMODPOW2C.suite,
    Tests.Instr.Arith.QMULMODPOW2R.suite,
    Tests.Instr.Arith.QMULMODR.suite,
    Tests.Instr.Arith.QMULRSHIFT.suite,
    Tests.Instr.Arith.QMULRSHIFTC.suite,
    Tests.Instr.Arith.QMULRSHIFTCMOD.suite,
    Tests.Instr.Arith.QMULRSHIFTMOD.suite,
    Tests.Instr.Arith.QMULRSHIFTR.suite,
    Tests.Instr.Arith.QMULRSHIFTRMOD.suite,
    Tests.Instr.Arith.QNEGATE.suite,
    Tests.Instr.Arith.QNEQ.suite,
    Tests.Instr.Arith.QNEQINT.suite,
    Tests.Instr.Arith.QNOT.suite,
    Tests.Instr.Arith.QOR.suite,
    Tests.Instr.Arith.QPOW2.suite,
    Tests.Instr.Arith.QRSHIFT.suite,
    Tests.Instr.Arith.QRSHIFTC.suite,
    Tests.Instr.Arith.QRSHIFTMOD.suite,
    Tests.Instr.Arith.QRSHIFTMODC.suite,
    Tests.Instr.Arith.QRSHIFTMODR.suite,
    Tests.Instr.Arith.QRSHIFTR.suite,
    Tests.Instr.Arith.QRSHIFT_ALT.suite,
    Tests.Instr.Arith.QRSHIFT_VAR.suite,
    Tests.Instr.Arith.QSGN.suite,
    Tests.Instr.Arith.QSUB.suite,
    Tests.Instr.Arith.QSUBR.suite,
    Tests.Instr.Arith.QUBITSIZE.suite,
    Tests.Instr.Arith.QUFITS.suite,
    Tests.Instr.Arith.QUFITSX.suite,
    Tests.Instr.Arith.QXOR.suite,
    Tests.Instr.Arith.RSHIFT.suite,
    Tests.Instr.Arith.RSHIFTC.suite,
    Tests.Instr.Arith.RSHIFTC_HASH.suite,
    Tests.Instr.Arith.RSHIFTC_HASH_MOD.suite,
    Tests.Instr.Arith.RSHIFTMOD.suite,
    Tests.Instr.Arith.RSHIFTMODC.suite,
    Tests.Instr.Arith.RSHIFTMODR.suite,
    Tests.Instr.Arith.RSHIFTR.suite,
    Tests.Instr.Arith.RSHIFTR_HASH.suite,
    Tests.Instr.Arith.RSHIFTR_HASH_MOD.suite,
    Tests.Instr.Arith.RSHIFT_ALT.suite,
    Tests.Instr.Arith.RSHIFT_HASH.suite,
    Tests.Instr.Arith.RSHIFT_HASH_MOD.suite,
    Tests.Instr.Arith.RSHIFT_VAR.suite,
    Tests.Instr.Arith.SGN.suite,
    Tests.Instr.Arith.SUB.suite,
    Tests.Instr.Arith.SUBR.suite,
    Tests.Instr.Arith.UBITSIZE.suite,
    Tests.Instr.Arith.UFITS.suite,
    Tests.Instr.Arith.UFITSX.suite,
    Tests.Instr.Arith.XOR.suite,
    Tests.Instr.Cell.BBITREFS.suite,
    Tests.Instr.Cell.BBITS.suite,
    Tests.Instr.Cell.BCHKBITREFS.suite,
    Tests.Instr.Cell.BCHKBITREFSQ.suite,
    Tests.Instr.Cell.BCHKBITS.suite,
    Tests.Instr.Cell.BCHKBITSQ.suite,
    Tests.Instr.Cell.BCHKBITSQ_VAR.suite,
    Tests.Instr.Cell.BCHKBITS_VAR.suite,
    Tests.Instr.Cell.BCHKREFS.suite,
    Tests.Instr.Cell.BCHKREFSQ.suite,
    Tests.Instr.Cell.BDEPTH.suite,
    Tests.Instr.Cell.BREFS.suite,
    Tests.Instr.Cell.BREMBITREFS.suite,
    Tests.Instr.Cell.BREMBITS.suite,
    Tests.Instr.Cell.BREMREFS.suite,
    Tests.Instr.Cell.BTOS.suite,
    Tests.Instr.Cell.CDEPTH.suite,
    Tests.Instr.Cell.CDEPTHI.suite,
    Tests.Instr.Cell.CDEPTHIX.suite,
    Tests.Instr.Cell.CHASHI.suite,
    Tests.Instr.Cell.CHASHIX.suite,
    Tests.Instr.Cell.CLEVEL.suite,
    Tests.Instr.Cell.CLEVELMASK.suite,
    Tests.Instr.Cell.CTOS.suite,
    Tests.Instr.Cell.ENDC.suite,
    Tests.Instr.Cell.ENDCST.suite,
    Tests.Instr.Cell.ENDS.suite,
    Tests.Instr.Cell.ENDXC.suite,
    Tests.Instr.Cell.LDGRAMS.suite,
    Tests.Instr.Cell.LDI.suite,
    Tests.Instr.Cell.LDILE4.suite,
    Tests.Instr.Cell.LDILE4Q.suite,
    Tests.Instr.Cell.LDILE8.suite,
    Tests.Instr.Cell.LDILE8Q.suite,
    Tests.Instr.Cell.LDIQ.suite,
    Tests.Instr.Cell.LDIX.suite,
    Tests.Instr.Cell.LDIXQ.suite,
    Tests.Instr.Cell.LDI_ALT.suite,
    Tests.Instr.Cell.LDMSGADDR.suite,
    Tests.Instr.Cell.LDMSGADDRQ.suite,
    Tests.Instr.Cell.LDONES.suite,
    Tests.Instr.Cell.LDOPTSTDADDR.suite,
    Tests.Instr.Cell.LDOPTSTDADDRQ.suite,
    Tests.Instr.Cell.LDREF.suite,
    Tests.Instr.Cell.LDREFRTOS.suite,
    Tests.Instr.Cell.LDSAME.suite,
    Tests.Instr.Cell.LDSLICE.suite,
    Tests.Instr.Cell.LDSLICEQ.suite,
    Tests.Instr.Cell.LDSLICEX.suite,
    Tests.Instr.Cell.LDSLICEXQ.suite,
    Tests.Instr.Cell.LDSLICE_ALT.suite,
    Tests.Instr.Cell.LDSTDADDR.suite,
    Tests.Instr.Cell.LDSTDADDRQ.suite,
    Tests.Instr.Cell.LDU.suite,
    Tests.Instr.Cell.LDULE4.suite,
    Tests.Instr.Cell.LDULE4Q.suite,
    Tests.Instr.Cell.LDULE8.suite,
    Tests.Instr.Cell.LDULE8Q.suite,
    Tests.Instr.Cell.LDUQ.suite,
    Tests.Instr.Cell.LDUX.suite,
    Tests.Instr.Cell.LDUXQ.suite,
    Tests.Instr.Cell.LDU_ALT.suite,
    Tests.Instr.Cell.LDVARINT16.suite,
    Tests.Instr.Cell.LDVARINT32.suite,
    Tests.Instr.Cell.LDVARUINT32.suite,
    Tests.Instr.Cell.LDZEROES.suite,
    Tests.Instr.Cell.NEWC.suite,
    Tests.Instr.Cell.PLDI.suite,
    Tests.Instr.Cell.PLDILE4.suite,
    Tests.Instr.Cell.PLDILE4Q.suite,
    Tests.Instr.Cell.PLDILE8.suite,
    Tests.Instr.Cell.PLDILE8Q.suite,
    Tests.Instr.Cell.PLDIQ.suite,
    Tests.Instr.Cell.PLDIX.suite,
    Tests.Instr.Cell.PLDIXQ.suite,
    Tests.Instr.Cell.PLDREFIDX.suite,
    Tests.Instr.Cell.PLDREFVAR.suite,
    Tests.Instr.Cell.PLDSLICE.suite,
    Tests.Instr.Cell.PLDSLICEQ.suite,
    Tests.Instr.Cell.PLDSLICEX.suite,
    Tests.Instr.Cell.PLDSLICEXQ.suite,
    Tests.Instr.Cell.PLDU.suite,
    Tests.Instr.Cell.PLDULE4.suite,
    Tests.Instr.Cell.PLDULE4Q.suite,
    Tests.Instr.Cell.PLDULE8.suite,
    Tests.Instr.Cell.PLDULE8Q.suite,
    Tests.Instr.Cell.PLDUQ.suite,
    Tests.Instr.Cell.PLDUX.suite,
    Tests.Instr.Cell.PLDUXQ.suite,
    Tests.Instr.Cell.PLDUZ.suite,
    Tests.Instr.Cell.PUSHCONT.suite,
    Tests.Instr.Cell.PUSHCONT_SHORT.suite,
    Tests.Instr.Cell.PUSHREF.suite,
    Tests.Instr.Cell.PUSHREFCONT.suite,
    Tests.Instr.Cell.PUSHREFSLICE.suite,
    Tests.Instr.Cell.PUSHSLICE.suite,
    Tests.Instr.Cell.PUSHSLICE_LONG.suite,
    Tests.Instr.Cell.PUSHSLICE_REFS.suite,
    Tests.Instr.Cell.SBITREFS.suite,
    Tests.Instr.Cell.SBITS.suite,
    Tests.Instr.Cell.SCHKBITREFS.suite,
    Tests.Instr.Cell.SCHKBITREFSQ.suite,
    Tests.Instr.Cell.SCHKBITS.suite,
    Tests.Instr.Cell.SCHKBITSQ.suite,
    Tests.Instr.Cell.SCHKREFS.suite,
    Tests.Instr.Cell.SCHKREFSQ.suite,
    Tests.Instr.Cell.SCUTFIRST.suite,
    Tests.Instr.Cell.SCUTLAST.suite,
    Tests.Instr.Cell.SDBEGINS.suite,
    Tests.Instr.Cell.SDBEGINSQ.suite,
    Tests.Instr.Cell.SDBEGINSX.suite,
    Tests.Instr.Cell.SDBEGINSXQ.suite,
    Tests.Instr.Cell.SDCNTLEAD0.suite,
    Tests.Instr.Cell.SDCNTLEAD1.suite,
    Tests.Instr.Cell.SDCNTTRAIL0.suite,
    Tests.Instr.Cell.SDCNTTRAIL1.suite,
    Tests.Instr.Cell.SDCUTFIRST.suite,
    Tests.Instr.Cell.SDCUTLAST.suite,
    Tests.Instr.Cell.SDEMPTY.suite,
    Tests.Instr.Cell.SDEPTH.suite,
    Tests.Instr.Cell.SDEQ.suite,
    Tests.Instr.Cell.SDFIRST.suite,
    Tests.Instr.Cell.SDLEXCMP.suite,
    Tests.Instr.Cell.SDPFX.suite,
    Tests.Instr.Cell.SDPFXREV.suite,
    Tests.Instr.Cell.SDPPFX.suite,
    Tests.Instr.Cell.SDPPFXREV.suite,
    Tests.Instr.Cell.SDPSFX.suite,
    Tests.Instr.Cell.SDPSFXREV.suite,
    Tests.Instr.Cell.SDSFX.suite,
    Tests.Instr.Cell.SDSFXREV.suite,
    Tests.Instr.Cell.SDSKIPFIRST.suite,
    Tests.Instr.Cell.SDSKIPLAST.suite,
    Tests.Instr.Cell.SDSUBSTR.suite,
    Tests.Instr.Cell.SEMPTY.suite,
    Tests.Instr.Cell.SPLIT.suite,
    Tests.Instr.Cell.SPLITQ.suite,
    Tests.Instr.Cell.SREFS.suite,
    Tests.Instr.Cell.SREMPTY.suite,
    Tests.Instr.Cell.SSKIPFIRST.suite,
    Tests.Instr.Cell.SSKIPLAST.suite,
    Tests.Instr.Cell.STB.suite,
    Tests.Instr.Cell.STBQ.suite,
    Tests.Instr.Cell.STBR.suite,
    Tests.Instr.Cell.STBREF.suite,
    Tests.Instr.Cell.STBREFQ.suite,
    Tests.Instr.Cell.STBREFR.suite,
    Tests.Instr.Cell.STBREFRQ.suite,
    Tests.Instr.Cell.STBRQ.suite,
    Tests.Instr.Cell.STGRAMS.suite,
    Tests.Instr.Cell.STI.suite,
    Tests.Instr.Cell.STILE4.suite,
    Tests.Instr.Cell.STILE8.suite,
    Tests.Instr.Cell.STIQ.suite,
    Tests.Instr.Cell.STIR.suite,
    Tests.Instr.Cell.STIRQ.suite,
    Tests.Instr.Cell.STIX.suite,
    Tests.Instr.Cell.STIXQ.suite,
    Tests.Instr.Cell.STIXR.suite,
    Tests.Instr.Cell.STIXRQ.suite,
    Tests.Instr.Cell.STI_ALT.suite,
    Tests.Instr.Cell.STONES.suite,
    Tests.Instr.Cell.STOPTSTDADDR.suite,
    Tests.Instr.Cell.STOPTSTDADDRQ.suite,
    Tests.Instr.Cell.STREF.suite,
    Tests.Instr.Cell.STREF2CONST.suite,
    Tests.Instr.Cell.STREFCONST.suite,
    Tests.Instr.Cell.STREFQ.suite,
    Tests.Instr.Cell.STREFR.suite,
    Tests.Instr.Cell.STREFRQ.suite,
    Tests.Instr.Cell.STREF_ALT.suite,
    Tests.Instr.Cell.STSAME.suite,
    Tests.Instr.Cell.STSLICE.suite,
    Tests.Instr.Cell.STSLICECONST.suite,
    Tests.Instr.Cell.STSLICEQ.suite,
    Tests.Instr.Cell.STSLICER.suite,
    Tests.Instr.Cell.STSLICERQ.suite,
    Tests.Instr.Cell.STSLICE_ALT.suite,
    Tests.Instr.Cell.STSTDADDR.suite,
    Tests.Instr.Cell.STSTDADDRQ.suite,
    Tests.Instr.Cell.STU.suite,
    Tests.Instr.Cell.STULE4.suite,
    Tests.Instr.Cell.STULE8.suite,
    Tests.Instr.Cell.STUQ.suite,
    Tests.Instr.Cell.STUR.suite,
    Tests.Instr.Cell.STURQ.suite,
    Tests.Instr.Cell.STUX.suite,
    Tests.Instr.Cell.STUXQ.suite,
    Tests.Instr.Cell.STUXR.suite,
    Tests.Instr.Cell.STUXRQ.suite,
    Tests.Instr.Cell.STU_ALT.suite,
    Tests.Instr.Cell.STVARINT16.suite,
    Tests.Instr.Cell.STVARINT32.suite,
    Tests.Instr.Cell.STVARUINT32.suite,
    Tests.Instr.Cell.STZEROES.suite,
    Tests.Instr.Cell.SUBSLICE.suite,
    Tests.Instr.Cell.XCTOS.suite,
    Tests.Instr.Cell.XLOAD.suite,
    Tests.Instr.Cell.XLOADQ.suite,
    Tests.Instr.Cont.AGAIN.suite,
    Tests.Instr.Cont.AGAINBRK.suite,
    Tests.Instr.Cont.AGAINEND.suite,
    Tests.Instr.Cont.AGAINENDBRK.suite,
    Tests.Instr.Cont.ATEXIT.suite,
    Tests.Instr.Cont.ATEXITALT.suite,
    Tests.Instr.Cont.BLESS.suite,
    Tests.Instr.Cont.BLESSARGS.suite,
    Tests.Instr.Cont.BLESSVARARGS.suite,
    Tests.Instr.Cont.BOOLAND.suite,
    Tests.Instr.Cont.BOOLEVAL.suite,
    Tests.Instr.Cont.BOOLOR.suite,
    Tests.Instr.Cont.CALLCC.suite,
    Tests.Instr.Cont.CALLCCARGS.suite,
    Tests.Instr.Cont.CALLCCVARARGS.suite,
    Tests.Instr.Cont.CALLDICT.suite,
    Tests.Instr.Cont.CALLDICT_LONG.suite,
    Tests.Instr.Cont.CALLREF.suite,
    Tests.Instr.Cont.CALLXARGS.suite,
    Tests.Instr.Cont.CALLXARGS_1.suite,
    Tests.Instr.Cont.CALLXVARARGS.suite,
    Tests.Instr.Cont.COMPOSBOTH.suite,
    Tests.Instr.Cont.CONDSEL.suite,
    Tests.Instr.Cont.CONDSELCHK.suite,
    Tests.Instr.Cont.EXECUTE.suite,
    Tests.Instr.Cont.IF.suite,
    Tests.Instr.Cont.IFBITJMP.suite,
    Tests.Instr.Cont.IFBITJMPREF.suite,
    Tests.Instr.Cont.IFELSE.suite,
    Tests.Instr.Cont.IFELSEREF.suite,
    Tests.Instr.Cont.IFJMP.suite,
    Tests.Instr.Cont.IFJMPREF.suite,
    Tests.Instr.Cont.IFNBITJMP.suite,
    Tests.Instr.Cont.IFNBITJMPREF.suite,
    Tests.Instr.Cont.IFNOT.suite,
    Tests.Instr.Cont.IFNOTJMP.suite,
    Tests.Instr.Cont.IFNOTJMPREF.suite,
    Tests.Instr.Cont.IFNOTREF.suite,
    Tests.Instr.Cont.IFNOTRET.suite,
    Tests.Instr.Cont.IFNOTRETALT.suite,
    Tests.Instr.Cont.IFREF.suite,
    Tests.Instr.Cont.IFREFELSE.suite,
    Tests.Instr.Cont.IFREFELSEREF.suite,
    Tests.Instr.Cont.IFRET.suite,
    Tests.Instr.Cont.IFRETALT.suite,
    Tests.Instr.Cont.INVERT.suite,
    Tests.Instr.Cont.JMPDICT.suite,
    Tests.Instr.Cont.JMPREF.suite,
    Tests.Instr.Cont.JMPREFDATA.suite,
    Tests.Instr.Cont.JMPX.suite,
    Tests.Instr.Cont.JMPXARGS.suite,
    Tests.Instr.Cont.JMPXDATA.suite,
    Tests.Instr.Cont.JMPXVARARGS.suite,
    Tests.Instr.Cont.POPCTR.suite,
    Tests.Instr.Cont.POPCTRX.suite,
    Tests.Instr.Cont.POPSAVE.suite,
    Tests.Instr.Cont.PREPAREDICT.suite,
    Tests.Instr.Cont.PUSHCTR.suite,
    Tests.Instr.Cont.PUSHCTRX.suite,
    Tests.Instr.Cont.REPEAT.suite,
    Tests.Instr.Cont.REPEATBRK.suite,
    Tests.Instr.Cont.REPEATEND.suite,
    Tests.Instr.Cont.REPEATENDBRK.suite,
    Tests.Instr.Cont.RET.suite,
    Tests.Instr.Cont.RETALT.suite,
    Tests.Instr.Cont.RETARGS.suite,
    Tests.Instr.Cont.RETBOOL.suite,
    Tests.Instr.Cont.RETDATA.suite,
    Tests.Instr.Cont.RETURNARGS.suite,
    Tests.Instr.Cont.RETURNVARARGS.suite,
    Tests.Instr.Cont.RETVARARGS.suite,
    Tests.Instr.Cont.RUNVM.suite,
    Tests.Instr.Cont.RUNVMX.suite,
    Tests.Instr.Cont.SAMEALT.suite,
    Tests.Instr.Cont.SAMEALTSAVE.suite,
    Tests.Instr.Cont.SAVEALTCTR.suite,
    Tests.Instr.Cont.SAVEBOTHCTR.suite,
    Tests.Instr.Cont.SAVECTR.suite,
    Tests.Instr.Cont.SETALTCTR.suite,
    Tests.Instr.Cont.SETCONTARGS.suite,
    Tests.Instr.Cont.SETCONTCTR.suite,
    Tests.Instr.Cont.SETCONTCTRMANY.suite,
    Tests.Instr.Cont.SETCONTCTRMANYX.suite,
    Tests.Instr.Cont.SETCONTCTRX.suite,
    Tests.Instr.Cont.SETCONTVARARGS.suite,
    Tests.Instr.Cont.SETEXITALT.suite,
    Tests.Instr.Cont.SETNUMVARARGS.suite,
    Tests.Instr.Cont.SETRETCTR.suite,
    Tests.Instr.Cont.THENRET.suite,
    Tests.Instr.Cont.THENRETALT.suite,
    Tests.Instr.Cont.UNTIL.suite,
    Tests.Instr.Cont.UNTILBRK.suite,
    Tests.Instr.Cont.UNTILEND.suite,
    Tests.Instr.Cont.UNTILENDBRK.suite,
    Tests.Instr.Cont.WHILE.suite,
    Tests.Instr.Cont.WHILEBRK.suite,
    Tests.Instr.Cont.WHILEEND.suite,
    Tests.Instr.Cont.WHILEENDBRK.suite,
    Tests.Instr.Crypto.BLS_AGGREGATE.suite,
    Tests.Instr.Crypto.BLS_AGGREGATEVERIFY.suite,
    Tests.Instr.Crypto.BLS_FASTAGGREGATEVERIFY.suite,
    Tests.Instr.Crypto.BLS_G1_ADD.suite,
    Tests.Instr.Crypto.BLS_G1_INGROUP.suite,
    Tests.Instr.Crypto.BLS_G1_ISZERO.suite,
    Tests.Instr.Crypto.BLS_G1_MUL.suite,
    Tests.Instr.Crypto.BLS_G1_MULTIEXP.suite,
    Tests.Instr.Crypto.BLS_G1_NEG.suite,
    Tests.Instr.Crypto.BLS_G1_SUB.suite,
    Tests.Instr.Crypto.BLS_G1_ZERO.suite,
    Tests.Instr.Crypto.BLS_G2_ADD.suite,
    Tests.Instr.Crypto.BLS_G2_INGROUP.suite,
    Tests.Instr.Crypto.BLS_G2_ISZERO.suite,
    Tests.Instr.Crypto.BLS_G2_MUL.suite,
    Tests.Instr.Crypto.BLS_G2_MULTIEXP.suite,
    Tests.Instr.Crypto.BLS_G2_NEG.suite,
    Tests.Instr.Crypto.BLS_G2_SUB.suite,
    Tests.Instr.Crypto.BLS_G2_ZERO.suite,
    Tests.Instr.Crypto.BLS_MAP_TO_G1.suite,
    Tests.Instr.Crypto.BLS_MAP_TO_G2.suite,
    Tests.Instr.Crypto.BLS_PAIRING.suite,
    Tests.Instr.Crypto.BLS_PUSHR.suite,
    Tests.Instr.Crypto.BLS_VERIFY.suite,
    Tests.Instr.Crypto.CHKSIGNS.suite,
    Tests.Instr.Crypto.CHKSIGNU.suite,
    Tests.Instr.Crypto.ECRECOVER.suite,
    Tests.Instr.Crypto.HASHBU.suite,
    Tests.Instr.Crypto.HASHCU.suite,
    Tests.Instr.Crypto.HASHEXT.suite,
    Tests.Instr.Crypto.HASHEXTA.suite,
    Tests.Instr.Crypto.HASHEXTAR.suite,
    Tests.Instr.Crypto.HASHEXTR.suite,
    Tests.Instr.Crypto.HASHSU.suite,
    Tests.Instr.Crypto.P256_CHKSIGNS.suite,
    Tests.Instr.Crypto.P256_CHKSIGNU.suite,
    Tests.Instr.Crypto.RIST255_ADD.suite,
    Tests.Instr.Crypto.RIST255_FROMHASH.suite,
    Tests.Instr.Crypto.RIST255_MUL.suite,
    Tests.Instr.Crypto.RIST255_MULBASE.suite,
    Tests.Instr.Crypto.RIST255_PUSHL.suite,
    Tests.Instr.Crypto.RIST255_QADD.suite,
    Tests.Instr.Crypto.RIST255_QMUL.suite,
    Tests.Instr.Crypto.RIST255_QMULBASE.suite,
    Tests.Instr.Crypto.RIST255_QSUB.suite,
    Tests.Instr.Crypto.RIST255_QVALIDATE.suite,
    Tests.Instr.Crypto.RIST255_SUB.suite,
    Tests.Instr.Crypto.RIST255_VALIDATE.suite,
    Tests.Instr.Crypto.SECP256K1_XONLY_PUBKEY_TWEAK_ADD.suite,
    Tests.Instr.Crypto.SHA256U.suite,
    Tests.Instr.Debug.DEBUG.suite,
    Tests.Instr.Debug.DEBUGSTR.suite,
    Tests.Instr.Debug.DEBUG_1.suite,
    Tests.Instr.Debug.DEBUG_2.suite,
    Tests.Instr.Debug.DUMP.suite,
    Tests.Instr.Debug.DUMPSTK.suite,
    Tests.Instr.Debug.EXTCALL.suite,
    Tests.Instr.Debug.STRDUMP.suite,
    Tests.Instr.Dict.DICTADD.suite,
    Tests.Instr.Dict.DICTADDB.suite,
    Tests.Instr.Dict.DICTADDGET.suite,
    Tests.Instr.Dict.DICTADDGETB.suite,
    Tests.Instr.Dict.DICTADDGETREF.suite,
    Tests.Instr.Dict.DICTADDREF.suite,
    Tests.Instr.Dict.DICTDEL.suite,
    Tests.Instr.Dict.DICTDELGET.suite,
    Tests.Instr.Dict.DICTDELGETREF.suite,
    Tests.Instr.Dict.DICTGET.suite,
    Tests.Instr.Dict.DICTGETNEXT.suite,
    Tests.Instr.Dict.DICTGETNEXTEQ.suite,
    Tests.Instr.Dict.DICTGETOPTREF.suite,
    Tests.Instr.Dict.DICTGETPREV.suite,
    Tests.Instr.Dict.DICTGETPREVEQ.suite,
    Tests.Instr.Dict.DICTGETREF.suite,
    Tests.Instr.Dict.DICTIADD.suite,
    Tests.Instr.Dict.DICTIADDB.suite,
    Tests.Instr.Dict.DICTIADDGET.suite,
    Tests.Instr.Dict.DICTIADDGETB.suite,
    Tests.Instr.Dict.DICTIADDGETREF.suite,
    Tests.Instr.Dict.DICTIADDREF.suite,
    Tests.Instr.Dict.DICTIDEL.suite,
    Tests.Instr.Dict.DICTIDELGET.suite,
    Tests.Instr.Dict.DICTIDELGETREF.suite,
    Tests.Instr.Dict.DICTIGET.suite,
    Tests.Instr.Dict.DICTIGETEXEC.suite,
    Tests.Instr.Dict.DICTIGETEXECZ.suite,
    Tests.Instr.Dict.DICTIGETJMP.suite,
    Tests.Instr.Dict.DICTIGETJMPZ.suite,
    Tests.Instr.Dict.DICTIGETNEXT.suite,
    Tests.Instr.Dict.DICTIGETNEXTEQ.suite,
    Tests.Instr.Dict.DICTIGETOPTREF.suite,
    Tests.Instr.Dict.DICTIGETPREV.suite,
    Tests.Instr.Dict.DICTIGETPREVEQ.suite,
    Tests.Instr.Dict.DICTIGETREF.suite,
    Tests.Instr.Dict.DICTIMAX.suite,
    Tests.Instr.Dict.DICTIMAXREF.suite,
    Tests.Instr.Dict.DICTIMIN.suite,
    Tests.Instr.Dict.DICTIMINREF.suite,
    Tests.Instr.Dict.DICTIREMMAX.suite,
    Tests.Instr.Dict.DICTIREMMAXREF.suite,
    Tests.Instr.Dict.DICTIREMMIN.suite,
    Tests.Instr.Dict.DICTIREMMINREF.suite,
    Tests.Instr.Dict.DICTIREPLACE.suite,
    Tests.Instr.Dict.DICTIREPLACEB.suite,
    Tests.Instr.Dict.DICTIREPLACEGET.suite,
    Tests.Instr.Dict.DICTIREPLACEGETB.suite,
    Tests.Instr.Dict.DICTIREPLACEGETREF.suite,
    Tests.Instr.Dict.DICTIREPLACEREF.suite,
    Tests.Instr.Dict.DICTISET.suite,
    Tests.Instr.Dict.DICTISETB.suite,
    Tests.Instr.Dict.DICTISETGET.suite,
    Tests.Instr.Dict.DICTISETGETB.suite,
    Tests.Instr.Dict.DICTISETGETOPTREF.suite,
    Tests.Instr.Dict.DICTISETGETREF.suite,
    Tests.Instr.Dict.DICTISETREF.suite,
    Tests.Instr.Dict.DICTMAX.suite,
    Tests.Instr.Dict.DICTMAXREF.suite,
    Tests.Instr.Dict.DICTMIN.suite,
    Tests.Instr.Dict.DICTMINREF.suite,
    Tests.Instr.Dict.DICTPUSHCONST.suite,
    Tests.Instr.Dict.DICTREMMAX.suite,
    Tests.Instr.Dict.DICTREMMAXREF.suite,
    Tests.Instr.Dict.DICTREMMIN.suite,
    Tests.Instr.Dict.DICTREMMINREF.suite,
    Tests.Instr.Dict.DICTREPLACE.suite,
    Tests.Instr.Dict.DICTREPLACEB.suite,
    Tests.Instr.Dict.DICTREPLACEGET.suite,
    Tests.Instr.Dict.DICTREPLACEGETB.suite,
    Tests.Instr.Dict.DICTREPLACEGETREF.suite,
    Tests.Instr.Dict.DICTREPLACEREF.suite,
    Tests.Instr.Dict.DICTSET.suite,
    Tests.Instr.Dict.DICTSETB.suite,
    Tests.Instr.Dict.DICTSETGET.suite,
    Tests.Instr.Dict.DICTSETGETB.suite,
    Tests.Instr.Dict.DICTSETGETOPTREF.suite,
    Tests.Instr.Dict.DICTSETGETREF.suite,
    Tests.Instr.Dict.DICTSETREF.suite,
    Tests.Instr.Dict.DICTUADD.suite,
    Tests.Instr.Dict.DICTUADDB.suite,
    Tests.Instr.Dict.DICTUADDGET.suite,
    Tests.Instr.Dict.DICTUADDGETB.suite,
    Tests.Instr.Dict.DICTUADDGETREF.suite,
    Tests.Instr.Dict.DICTUADDREF.suite,
    Tests.Instr.Dict.DICTUDEL.suite,
    Tests.Instr.Dict.DICTUDELGET.suite,
    Tests.Instr.Dict.DICTUDELGETREF.suite,
    Tests.Instr.Dict.DICTUGET.suite,
    Tests.Instr.Dict.DICTUGETEXEC.suite,
    Tests.Instr.Dict.DICTUGETEXECZ.suite,
    Tests.Instr.Dict.DICTUGETJMP.suite,
    Tests.Instr.Dict.DICTUGETJMPZ.suite,
    Tests.Instr.Dict.DICTUGETNEXT.suite,
    Tests.Instr.Dict.DICTUGETNEXTEQ.suite,
    Tests.Instr.Dict.DICTUGETOPTREF.suite,
    Tests.Instr.Dict.DICTUGETPREV.suite,
    Tests.Instr.Dict.DICTUGETPREVEQ.suite,
    Tests.Instr.Dict.DICTUGETREF.suite,
    Tests.Instr.Dict.DICTUMAX.suite,
    Tests.Instr.Dict.DICTUMAXREF.suite,
    Tests.Instr.Dict.DICTUMIN.suite,
    Tests.Instr.Dict.DICTUMINREF.suite,
    Tests.Instr.Dict.DICTUREMMAX.suite,
    Tests.Instr.Dict.DICTUREMMAXREF.suite,
    Tests.Instr.Dict.DICTUREMMIN.suite,
    Tests.Instr.Dict.DICTUREMMINREF.suite,
    Tests.Instr.Dict.DICTUREPLACE.suite,
    Tests.Instr.Dict.DICTUREPLACEB.suite,
    Tests.Instr.Dict.DICTUREPLACEGET.suite,
    Tests.Instr.Dict.DICTUREPLACEGETB.suite,
    Tests.Instr.Dict.DICTUREPLACEGETREF.suite,
    Tests.Instr.Dict.DICTUREPLACEREF.suite,
    Tests.Instr.Dict.DICTUSET.suite,
    Tests.Instr.Dict.DICTUSETB.suite,
    Tests.Instr.Dict.DICTUSETGET.suite,
    Tests.Instr.Dict.DICTUSETGETB.suite,
    Tests.Instr.Dict.DICTUSETGETOPTREF.suite,
    Tests.Instr.Dict.DICTUSETGETREF.suite,
    Tests.Instr.Dict.DICTUSETREF.suite,
    Tests.Instr.Dict.LDDICT.suite,
    Tests.Instr.Dict.LDDICTQ.suite,
    Tests.Instr.Dict.LDDICTS.suite,
    Tests.Instr.Dict.PFXDICTADD.suite,
    Tests.Instr.Dict.PFXDICTDEL.suite,
    Tests.Instr.Dict.PFXDICTGET.suite,
    Tests.Instr.Dict.PFXDICTGETEXEC.suite,
    Tests.Instr.Dict.PFXDICTGETJMP.suite,
    Tests.Instr.Dict.PFXDICTGETQ.suite,
    Tests.Instr.Dict.PFXDICTREPLACE.suite,
    Tests.Instr.Dict.PFXDICTSET.suite,
    Tests.Instr.Dict.PFXDICTSWITCH.suite,
    Tests.Instr.Dict.PLDDICT.suite,
    Tests.Instr.Dict.PLDDICTQ.suite,
    Tests.Instr.Dict.PLDDICTS.suite,
    Tests.Instr.Dict.SKIPDICT.suite,
    Tests.Instr.Dict.STDICT.suite,
    Tests.Instr.Dict.SUBDICTGET.suite,
    Tests.Instr.Dict.SUBDICTIGET.suite,
    Tests.Instr.Dict.SUBDICTIRPGET.suite,
    Tests.Instr.Dict.SUBDICTRPGET.suite,
    Tests.Instr.Dict.SUBDICTUGET.suite,
    Tests.Instr.Dict.SUBDICTURPGET.suite,
    Tests.Instr.Exception.THROW.suite,
    Tests.Instr.Exception.THROWANY.suite,
    Tests.Instr.Exception.THROWANYIF.suite,
    Tests.Instr.Exception.THROWANYIFNOT.suite,
    Tests.Instr.Exception.THROWARG.suite,
    Tests.Instr.Exception.THROWARGANY.suite,
    Tests.Instr.Exception.THROWARGANYIF.suite,
    Tests.Instr.Exception.THROWARGANYIFNOT.suite,
    Tests.Instr.Exception.THROWARGIF.suite,
    Tests.Instr.Exception.THROWARGIFNOT.suite,
    Tests.Instr.Exception.THROWIF.suite,
    Tests.Instr.Exception.THROWIFNOT.suite,
    Tests.Instr.Exception.THROWIFNOT_SHORT.suite,
    Tests.Instr.Exception.THROWIF_SHORT.suite,
    Tests.Instr.Exception.THROW_SHORT.suite,
    Tests.Instr.Exception.TRY.suite,
    Tests.Instr.Exception.TRYARGS.suite,
    Tests.Instr.Flow.SETCP.suite,
    Tests.Instr.Flow.SETCPX.suite,
    Tests.Instr.Flow.SETCP_SHORT.suite,
    Tests.Instr.Misc.CDATASIZE.suite,
    Tests.Instr.Misc.CDATASIZEQ.suite,
    Tests.Instr.Misc.SDATASIZE.suite,
    Tests.Instr.Misc.SDATASIZEQ.suite,
    Tests.Instr.Msg.CHANGELIB.suite,
    Tests.Instr.Msg.RAWRESERVE.suite,
    Tests.Instr.Msg.RAWRESERVEX.suite,
    Tests.Instr.Msg.SENDMSG.suite,
    Tests.Instr.Msg.SENDRAWMSG.suite,
    Tests.Instr.Msg.SETCODE.suite,
    Tests.Instr.Msg.SETLIBCODE.suite,
    Tests.Instr.Stack.BLKDROP.suite,
    Tests.Instr.Stack.BLKDROP2.suite,
    Tests.Instr.Stack.BLKPUSH.suite,
    Tests.Instr.Stack.BLKSWAP.suite,
    Tests.Instr.Stack.BLKSWX.suite,
    Tests.Instr.Stack.CHKDEPTH.suite,
    Tests.Instr.Stack.DEPTH.suite,
    Tests.Instr.Stack.DROP.suite,
    Tests.Instr.Stack.DROPX.suite,
    Tests.Instr.Stack.DUP.suite,
    Tests.Instr.Stack.NIP.suite,
    Tests.Instr.Stack.NOP.suite,
    Tests.Instr.Stack.ONLYTOPX.suite,
    Tests.Instr.Stack.ONLYX.suite,
    Tests.Instr.Stack.OP_2DROP.suite,
    Tests.Instr.Stack.OP_2DUP.suite,
    Tests.Instr.Stack.OP_2OVER.suite,
    Tests.Instr.Stack.OP_2SWAP.suite,
    Tests.Instr.Stack.OVER.suite,
    Tests.Instr.Stack.PICK.suite,
    Tests.Instr.Stack.POP.suite,
    Tests.Instr.Stack.POP_LONG.suite,
    Tests.Instr.Stack.PU2XC.suite,
    Tests.Instr.Stack.PUSH.suite,
    Tests.Instr.Stack.PUSH2.suite,
    Tests.Instr.Stack.PUSH3.suite,
    Tests.Instr.Stack.PUSH_LONG.suite,
    Tests.Instr.Stack.PUXC.suite,
    Tests.Instr.Stack.PUXC2.suite,
    Tests.Instr.Stack.PUXCPU.suite,
    Tests.Instr.Stack.REVERSE.suite,
    Tests.Instr.Stack.REVX.suite,
    Tests.Instr.Stack.ROLL.suite,
    Tests.Instr.Stack.ROLLREV.suite,
    Tests.Instr.Stack.ROT.suite,
    Tests.Instr.Stack.ROTREV.suite,
    Tests.Instr.Stack.SWAP.suite,
    Tests.Instr.Stack.TUCK.suite,
    Tests.Instr.Stack.XC2PU.suite,
    Tests.Instr.Stack.XCHG2.suite,
    Tests.Instr.Stack.XCHG3.suite,
    Tests.Instr.Stack.XCHG3_ALT.suite,
    Tests.Instr.Stack.XCHGX.suite,
    Tests.Instr.Stack.XCHG_0I.suite,
    Tests.Instr.Stack.XCHG_0I_LONG.suite,
    Tests.Instr.Stack.XCHG_1I.suite,
    Tests.Instr.Stack.XCHG_IJ.suite,
    Tests.Instr.Stack.XCPU.suite,
    Tests.Instr.Stack.XCPU2.suite,
    Tests.Instr.Stack.XCPUXC.suite,
    Tests.Instr.TonEnv.ACCEPT.suite,
    Tests.Instr.TonEnv.ADDRAND.suite,
    Tests.Instr.TonEnv.BALANCE.suite,
    Tests.Instr.TonEnv.BLOCKLT.suite,
    Tests.Instr.TonEnv.COMMIT.suite,
    Tests.Instr.TonEnv.CONFIGDICT.suite,
    Tests.Instr.TonEnv.CONFIGOPTPARAM.suite,
    Tests.Instr.TonEnv.CONFIGPARAM.suite,
    Tests.Instr.TonEnv.CONFIGROOT.suite,
    Tests.Instr.TonEnv.DUEPAYMENT.suite,
    Tests.Instr.TonEnv.GASCONSUMED.suite,
    Tests.Instr.TonEnv.GETFORWARDFEE.suite,
    Tests.Instr.TonEnv.GETFORWARDFEESIMPLE.suite,
    Tests.Instr.TonEnv.GETGASFEE.suite,
    Tests.Instr.TonEnv.GETGASFEESIMPLE.suite,
    Tests.Instr.TonEnv.GETGLOB.suite,
    Tests.Instr.TonEnv.GETGLOBVAR.suite,
    Tests.Instr.TonEnv.GETORIGINALFWDFEE.suite,
    Tests.Instr.TonEnv.GETPARAM.suite,
    Tests.Instr.TonEnv.GETPARAMLONG.suite,
    Tests.Instr.TonEnv.GETPARAMLONG2.suite,
    Tests.Instr.TonEnv.GETPRECOMPILEDGAS.suite,
    Tests.Instr.TonEnv.GETSTORAGEFEE.suite,
    Tests.Instr.TonEnv.GLOBALID.suite,
    Tests.Instr.TonEnv.INCOMINGVALUE.suite,
    Tests.Instr.TonEnv.INMSGPARAM.suite,
    Tests.Instr.TonEnv.INMSGPARAMS.suite,
    Tests.Instr.TonEnv.INMSG_BOUNCE.suite,
    Tests.Instr.TonEnv.INMSG_BOUNCED.suite,
    Tests.Instr.TonEnv.INMSG_FWDFEE.suite,
    Tests.Instr.TonEnv.INMSG_LT.suite,
    Tests.Instr.TonEnv.INMSG_ORIGVALUE.suite,
    Tests.Instr.TonEnv.INMSG_SRC.suite,
    Tests.Instr.TonEnv.INMSG_STATEINIT.suite,
    Tests.Instr.TonEnv.INMSG_UTIME.suite,
    Tests.Instr.TonEnv.INMSG_VALUE.suite,
    Tests.Instr.TonEnv.INMSG_VALUEEXTRA.suite,
    Tests.Instr.TonEnv.LTIME.suite,
    Tests.Instr.TonEnv.MYADDR.suite,
    Tests.Instr.TonEnv.MYCODE.suite,
    Tests.Instr.TonEnv.NOW.suite,
    Tests.Instr.TonEnv.PARSEMSGADDR.suite,
    Tests.Instr.TonEnv.PARSEMSGADDRQ.suite,
    Tests.Instr.TonEnv.PREVBLOCKSINFOTUPLE.suite,
    Tests.Instr.TonEnv.PREVKEYBLOCK.suite,
    Tests.Instr.TonEnv.PREVMCBLOCKS.suite,
    Tests.Instr.TonEnv.PREVMCBLOCKS_100.suite,
    Tests.Instr.TonEnv.RAND.suite,
    Tests.Instr.TonEnv.RANDSEED.suite,
    Tests.Instr.TonEnv.RANDU256.suite,
    Tests.Instr.TonEnv.REWRITESTDADDR.suite,
    Tests.Instr.TonEnv.REWRITESTDADDRQ.suite,
    Tests.Instr.TonEnv.REWRITEVARADDR.suite,
    Tests.Instr.TonEnv.REWRITEVARADDRQ.suite,
    Tests.Instr.TonEnv.SETGASLIMIT.suite,
    Tests.Instr.TonEnv.SETGLOB.suite,
    Tests.Instr.TonEnv.SETGLOBVAR.suite,
    Tests.Instr.TonEnv.SETRAND.suite,
    Tests.Instr.TonEnv.STORAGEFEES.suite,
    Tests.Instr.TonEnv.UNPACKEDCONFIGTUPLE.suite,
    Tests.Instr.Tuple.EXPLODE.suite,
    Tests.Instr.Tuple.EXPLODEVAR.suite,
    Tests.Instr.Tuple.INDEX.suite,
    Tests.Instr.Tuple.INDEX2.suite,
    Tests.Instr.Tuple.INDEX3.suite,
    Tests.Instr.Tuple.INDEXQ.suite,
    Tests.Instr.Tuple.INDEXVAR.suite,
    Tests.Instr.Tuple.INDEXVARQ.suite,
    Tests.Instr.Tuple.ISNULL.suite,
    Tests.Instr.Tuple.ISTUPLE.suite,
    Tests.Instr.Tuple.LAST.suite,
    Tests.Instr.Tuple.NULLROTRIF.suite,
    Tests.Instr.Tuple.NULLROTRIF2.suite,
    Tests.Instr.Tuple.NULLROTRIFNOT.suite,
    Tests.Instr.Tuple.NULLROTRIFNOT2.suite,
    Tests.Instr.Tuple.NULLSWAPIF.suite,
    Tests.Instr.Tuple.NULLSWAPIF2.suite,
    Tests.Instr.Tuple.NULLSWAPIFNOT.suite,
    Tests.Instr.Tuple.NULLSWAPIFNOT2.suite,
    Tests.Instr.Tuple.PUSHNULL.suite,
    Tests.Instr.Tuple.QTLEN.suite,
    Tests.Instr.Tuple.SETINDEX.suite,
    Tests.Instr.Tuple.SETINDEXQ.suite,
    Tests.Instr.Tuple.SETINDEXVAR.suite,
    Tests.Instr.Tuple.SETINDEXVARQ.suite,
    Tests.Instr.Tuple.TLEN.suite,
    Tests.Instr.Tuple.TPOP.suite,
    Tests.Instr.Tuple.TPUSH.suite,
    Tests.Instr.Tuple.TUPLE.suite,
    Tests.Instr.Tuple.TUPLEVAR.suite,
    Tests.Instr.Tuple.UNPACKFIRST.suite,
    Tests.Instr.Tuple.UNPACKFIRSTVAR.suite,
    Tests.Instr.Tuple.UNTUPLE.suite,
    Tests.Instr.Tuple.UNTUPLEVAR.suite,
  ]

end Tests
