#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


CATEGORY_FAMILY = {
    "address": "TonEnv",
    "arithmetic": "Arith",
    "basic_gas": "TonEnv",
    "cell": "Cell",
    "codepage": "Flow",
    "config": "TonEnv",
    "continuation": "Cont",
    "crypto": "Crypto",
    "debug": "Debug",
    "dictionary": "Dict",
    "exception": "Exception",
    "globals": "TonEnv",
    "message": "Msg",
    "misc": "Misc",
    "prng": "TonEnv",
    "stack": "Stack",
    "tuple": "Tuple",
}


def sanitize_module_name(name: str) -> str:
    out = name.replace("#", "_HASH_")
    out = re.sub(r"[^A-Za-z0-9_]", "_", out)
    out = re.sub(r"_+", "_", out).strip("_")
    if not out:
        out = "OP"
    if out[0].isdigit():
        out = f"OP_{out}"
    return out


def unique_module_name(base: str, used: set[str]) -> str:
    if base not in used:
        used.add(base)
        return base
    i = 2
    while True:
        cand = f"{base}_{i}"
        if cand not in used:
            used.add(cand)
            return cand
        i += 1


def render_skeleton(family: str, module: str, instr_name: str) -> str:
    ns = f"Tests.Instr.{family}.{module}"
    return "\n".join(
        [
            "import Tests.Harness.Registry",
            "import TvmLean.Spec.Index",
            "",
            "open TvmLean",
            "open Tests",
            "",
            f"namespace {ns}",
            "",
            "def suite : InstrSuite where",
            f"  id := {{ name := \"{instr_name}\" }}",
            "  unit := #[]",
            "  oracle := #[]",
            "  fuzz := #[]",
            "",
            "initialize registerSuite suite",
            "",
            f"end {ns}",
            "",
        ]
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--index",
        default="docs/progress/tvm_spec_index.json",
        help="Path to tvm_spec_index.json (pinned snapshot in this repo).",
    )
    ap.add_argument(
        "--out-dir",
        default="Tests",
        help="Output directory for generated tests tree.",
    )
    ap.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing instruction skeleton files.",
    )
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    index_path = (repo_root / args.index).resolve()
    out_dir = (repo_root / args.out_dir).resolve()

    with index_path.open("r", encoding="utf-8") as f:
        spec = json.load(f)

    tvm_instrs = spec.get("tvm_instructions", [])
    if not isinstance(tvm_instrs, list):
        raise SystemExit(f"{index_path} has unexpected format (tvm_instructions is not a list)")

    instr_dir = out_dir / "Instr"
    modules: list[tuple[str, str]] = []
    used_by_family: dict[str, set[str]] = {}

    for ins in sorted(tvm_instrs, key=lambda x: (x.get("category", ""), x.get("name", ""))):
        category = ins.get("category")
        name = ins.get("name")
        if not isinstance(category, str) or not isinstance(name, str):
            continue

        family = CATEGORY_FAMILY.get(category, "Misc")
        used = used_by_family.setdefault(family, set())
        mod_name = unique_module_name(sanitize_module_name(name), used)

        rel = Path(family) / f"{mod_name}.lean"
        path = instr_dir / rel
        modules.append((family, mod_name))

        if path.exists() and not args.overwrite:
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_skeleton(family, mod_name, name), encoding="utf-8")

    all_path = out_dir / "All.lean"
    all_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("-- Auto-generated by tools/gen_test_scaffold.py")
    lines.append("")
    lines.append("import Tests.Harness.Registry")
    for family, module in sorted(modules, key=lambda x: (x[0], x[1])):
        lines.append(f"import Tests.Instr.{family}.{module}")
    lines.append("")
    lines.append("open Tests")
    lines.append("")
    lines.append("namespace Tests")
    lines.append("")
    lines.append("def allInstrSuites : Array InstrSuite :=")
    lines.append("  #[")
    for family, module in sorted(modules, key=lambda x: (x[0], x[1])):
        lines.append(f"    Tests.Instr.{family}.{module}.suite,")
    lines.append("  ]")
    lines.append("")
    lines.append("end Tests")
    lines.append("")
    all_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote instruction skeletons under {instr_dir}")
    print(f"wrote {all_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
