#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path


CATEGORY_DIR = {
    "address": "Address",
    "arithmetic": "Arithmetic",
    "basic_gas": "BasicGas",
    "cell": "Cell",
    "codepage": "Codepage",
    "config": "Config",
    "continuation": "Continuation",
    "crypto": "Crypto",
    "debug": "Debug",
    "dictionary": "Dictionary",
    "exception": "Exception",
    "globals": "Globals",
    "message": "Message",
    "misc": "Misc",
    "prng": "Prng",
    "stack": "Stack",
    "tuple": "Tuple",
}


def sanitize_name(name: str) -> str:
    out = name.replace("#", "_HASH_")
    if out and out[0].isdigit():
        out = "OP_" + out
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--index",
        default="docs/progress/tvm_spec_index.json",
        help="Path to tvm_spec_index.json (pinned snapshot in this repo).",
    )
    ap.add_argument(
        "--out-dir",
        default="Tests",
        help="Output directory for generated test stubs.",
    )
    ap.add_argument(
        "--write-all",
        action="store_true",
        help="Overwrite Tests/All.lean with a generated import list.",
    )
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    index_path = (repo_root / args.index).resolve()
    out_dir = (repo_root / args.out_dir).resolve()

    with index_path.open("r", encoding="utf-8") as f:
        spec = json.load(f)

    tvm_instrs = spec.get("tvm_instructions", [])
    if not isinstance(tvm_instrs, list):
        raise SystemExit(f"{index_path} has unexpected format (tvm_instructions is not a list)")

    modules: list[tuple[str, str]] = []

    for ins in tvm_instrs:
        category = ins.get("category")
        name = ins.get("name")
        if not isinstance(category, str) or not isinstance(name, str):
            continue

        cat_dir = CATEGORY_DIR.get(category)
        if cat_dir is None:
            raise SystemExit(f"Unknown category '{category}' in {index_path}")

        mod_name = sanitize_name(name)
        rel = Path(cat_dir) / f"{mod_name}.lean"
        path = out_dir / rel
        modules.append((cat_dir, mod_name))

        if path.exists():
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            f"-- Auto-generated stub for TVM instruction {name} (category: {category}).\n",
            encoding="utf-8",
        )

    if args.write_all:
        all_path = out_dir / "All.lean"
        all_path.parent.mkdir(parents=True, exist_ok=True)
        modules_sorted = sorted(modules, key=lambda x: (x[0], x[1]))
        lines: list[str] = []
        lines.append("-- This file is auto-generated by `tools/gen_test_scaffold.py --write-all`.")
        lines.append("-- It is intended to be stable/append-only to reduce merge conflicts.")
        lines.append("")
        lines.append("import Tests.Boc")
        lines.append("import Tests.Counter")
        lines.append("")
        for cat_dir, mod_name in modules_sorted:
            lines.append(f"import Tests.{cat_dir}.{mod_name}")
        lines.append("")
        all_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

